/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
} from '../models/ApiError';
import {
    type BulkMessageRequest,
    BulkMessageRequestFromJSON,
    BulkMessageRequestToJSON,
} from '../models/BulkMessageRequest';
import {
    type BulkMessageResponse,
    BulkMessageResponseFromJSON,
    BulkMessageResponseToJSON,
} from '../models/BulkMessageResponse';
import {
    type ConnectionStatusResponse,
    ConnectionStatusResponseFromJSON,
    ConnectionStatusResponseToJSON,
} from '../models/ConnectionStatusResponse';
import {
    type DeliveryStatusResponse,
    DeliveryStatusResponseFromJSON,
    DeliveryStatusResponseToJSON,
} from '../models/DeliveryStatusResponse';
import {
    type ResumeDeliveryResponse,
    ResumeDeliveryResponseFromJSON,
    ResumeDeliveryResponseToJSON,
} from '../models/ResumeDeliveryResponse';
import {
    type SendMessageRequest,
    SendMessageRequestFromJSON,
    SendMessageRequestToJSON,
} from '../models/SendMessageRequest';
import {
    type SendMessageResponse,
    SendMessageResponseFromJSON,
    SendMessageResponseToJSON,
} from '../models/SendMessageResponse';

export interface GetConnectionStatusRequest {
    /**
     * 
     */
    whatsappAccountId: string;
}

export interface GetDeliveryStatusRequest {
    /**
     * 
     */
    whatsappAccountId: string;
}

export interface ResumeDeliveryRequest {
    /**
     * 
     */
    whatsappAccountId: string;
}

export interface SendBulkMessagesRequest {
    /**
     * Stable unique key for this batch. Each recipient is deduplicated independently.
     */
    idempotencyKey: string;
    /**
     * 
     */
    bulkMessageRequest: BulkMessageRequest;
}

export interface SendMessageOperationRequest {
    /**
     * Stable unique key for this business message. Reuse it when retrying the same request.
     */
    idempotencyKey: string;
    /**
     * 
     */
    sendMessageRequest: SendMessageRequest;
}

/**
 * MessagingApi - interface
 * 
 * @export
 * @interface MessagingApiInterface
 */
export interface MessagingApiInterface {
    /**
     * Creates request options for getConnectionStatus without sending the request
     * @param {string} whatsappAccountId 
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    getConnectionStatusRequestOpts(requestParameters: GetConnectionStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Check live WhatsApp connection status
     * @param {string} whatsappAccountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    getConnectionStatusRaw(requestParameters: GetConnectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionStatusResponse>>;

    /**
     * Check live WhatsApp connection status
     */
    getConnectionStatus(requestParameters: GetConnectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionStatusResponse>;

    /**
     * Creates request options for getDeliveryStatus without sending the request
     * @param {string} whatsappAccountId 
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    getDeliveryStatusRequestOpts(requestParameters: GetDeliveryStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get outbound delivery counts for an account
     * @param {string} whatsappAccountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    getDeliveryStatusRaw(requestParameters: GetDeliveryStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeliveryStatusResponse>>;

    /**
     * Get outbound delivery counts for an account
     */
    getDeliveryStatus(requestParameters: GetDeliveryStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeliveryStatusResponse>;

    /**
     * Creates request options for resumeDelivery without sending the request
     * @param {string} whatsappAccountId 
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    resumeDeliveryRequestOpts(requestParameters: ResumeDeliveryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Requeue pending outbound messages after reconnect
     * @param {string} whatsappAccountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    resumeDeliveryRaw(requestParameters: ResumeDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResumeDeliveryResponse>>;

    /**
     * Requeue pending outbound messages after reconnect
     */
    resumeDelivery(requestParameters: ResumeDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResumeDeliveryResponse>;

    /**
     * Creates request options for sendBulkMessages without sending the request
     * @param {string} idempotencyKey Stable unique key for this batch. Each recipient is deduplicated independently.
     * @param {BulkMessageRequest} bulkMessageRequest 
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    sendBulkMessagesRequestOpts(requestParameters: SendBulkMessagesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Queue the same message for many recipients
     * @param {string} idempotencyKey Stable unique key for this batch. Each recipient is deduplicated independently.
     * @param {BulkMessageRequest} bulkMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    sendBulkMessagesRaw(requestParameters: SendBulkMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkMessageResponse>>;

    /**
     * Queue the same message for many recipients
     */
    sendBulkMessages(requestParameters: SendBulkMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkMessageResponse>;

    /**
     * Creates request options for sendMessage without sending the request
     * @param {string} idempotencyKey Stable unique key for this business message. Reuse it when retrying the same request.
     * @param {SendMessageRequest} sendMessageRequest 
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    sendMessageRequestOpts(requestParameters: SendMessageOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Send a WhatsApp message using an API key
     * @param {string} idempotencyKey Stable unique key for this business message. Reuse it when retrying the same request.
     * @param {SendMessageRequest} sendMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApiInterface
     */
    sendMessageRaw(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMessageResponse>>;

    /**
     * Send a WhatsApp message using an API key
     */
    sendMessage(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMessageResponse>;

}

/**
 * 
 */
export class MessagingApi extends runtime.BaseAPI implements MessagingApiInterface {

    /**
     * Creates request options for getConnectionStatus without sending the request
     */
    async getConnectionStatusRequestOpts(requestParameters: GetConnectionStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['whatsappAccountId'] == null) {
            throw new runtime.RequiredError(
                'whatsappAccountId',
                'Required parameter "whatsappAccountId" was null or undefined when calling getConnectionStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyHeader authentication
        }


        let urlPath = `/api/v1/messages/accounts/{whatsappAccountId}/connection-status`;
        urlPath = urlPath.replace('{whatsappAccountId}', encodeURIComponent(String(requestParameters['whatsappAccountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Check live WhatsApp connection status
     */
    async getConnectionStatusRaw(requestParameters: GetConnectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionStatusResponse>> {
        const requestOptions = await this.getConnectionStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Check live WhatsApp connection status
     */
    async getConnectionStatus(requestParameters: GetConnectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionStatusResponse> {
        const response = await this.getConnectionStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDeliveryStatus without sending the request
     */
    async getDeliveryStatusRequestOpts(requestParameters: GetDeliveryStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['whatsappAccountId'] == null) {
            throw new runtime.RequiredError(
                'whatsappAccountId',
                'Required parameter "whatsappAccountId" was null or undefined when calling getDeliveryStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyHeader authentication
        }


        let urlPath = `/api/v1/messages/accounts/{whatsappAccountId}/delivery-status`;
        urlPath = urlPath.replace('{whatsappAccountId}', encodeURIComponent(String(requestParameters['whatsappAccountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get outbound delivery counts for an account
     */
    async getDeliveryStatusRaw(requestParameters: GetDeliveryStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeliveryStatusResponse>> {
        const requestOptions = await this.getDeliveryStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeliveryStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get outbound delivery counts for an account
     */
    async getDeliveryStatus(requestParameters: GetDeliveryStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeliveryStatusResponse> {
        const response = await this.getDeliveryStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resumeDelivery without sending the request
     */
    async resumeDeliveryRequestOpts(requestParameters: ResumeDeliveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['whatsappAccountId'] == null) {
            throw new runtime.RequiredError(
                'whatsappAccountId',
                'Required parameter "whatsappAccountId" was null or undefined when calling resumeDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyHeader authentication
        }


        let urlPath = `/api/v1/messages/accounts/{whatsappAccountId}/resume`;
        urlPath = urlPath.replace('{whatsappAccountId}', encodeURIComponent(String(requestParameters['whatsappAccountId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Requeue pending outbound messages after reconnect
     */
    async resumeDeliveryRaw(requestParameters: ResumeDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResumeDeliveryResponse>> {
        const requestOptions = await this.resumeDeliveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResumeDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Requeue pending outbound messages after reconnect
     */
    async resumeDelivery(requestParameters: ResumeDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResumeDeliveryResponse> {
        const response = await this.resumeDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendBulkMessages without sending the request
     */
    async sendBulkMessagesRequestOpts(requestParameters: SendBulkMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling sendBulkMessages().'
            );
        }

        if (requestParameters['bulkMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkMessageRequest',
                'Required parameter "bulkMessageRequest" was null or undefined when calling sendBulkMessages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyHeader authentication
        }


        let urlPath = `/api/v1/messages/bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkMessageRequestToJSON(requestParameters['bulkMessageRequest']),
        };
    }

    /**
     * Queue the same message for many recipients
     */
    async sendBulkMessagesRaw(requestParameters: SendBulkMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkMessageResponse>> {
        const requestOptions = await this.sendBulkMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkMessageResponseFromJSON(jsonValue));
    }

    /**
     * Queue the same message for many recipients
     */
    async sendBulkMessages(requestParameters: SendBulkMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkMessageResponse> {
        const response = await this.sendBulkMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendMessage without sending the request
     */
    async sendMessageRequestOpts(requestParameters: SendMessageOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling sendMessage().'
            );
        }

        if (requestParameters['sendMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'sendMessageRequest',
                'Required parameter "sendMessageRequest" was null or undefined when calling sendMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyHeader authentication
        }


        let urlPath = `/api/v1/messages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendMessageRequestToJSON(requestParameters['sendMessageRequest']),
        };
    }

    /**
     * Send a WhatsApp message using an API key
     */
    async sendMessageRaw(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendMessageResponse>> {
        const requestOptions = await this.sendMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendMessageResponseFromJSON(jsonValue));
    }

    /**
     * Send a WhatsApp message using an API key
     */
    async sendMessage(requestParameters: SendMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendMessageResponse> {
        const response = await this.sendMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
