=begin
#Paygham Messaging API

#Public server-side API for sending WhatsApp messages and monitoring delivery.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Paygham
  class DeliveryStatus < ApiModelBase
    attr_accessor :account_id

    attr_accessor :account_status

    # QUEUED + SENDING outbound messages
    attr_accessor :pending

    attr_accessor :sent

    attr_accessor :failed

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'account_status' => :'accountStatus',
        :'pending' => :'pending',
        :'sent' => :'sent',
        :'failed' => :'failed'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'account_status' => :'String',
        :'pending' => :'Integer',
        :'sent' => :'Integer',
        :'failed' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Paygham::DeliveryStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Paygham::DeliveryStatus`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'account_status')
        self.account_status = attributes[:'account_status']
      else
        self.account_status = nil
      end

      if attributes.key?(:'pending')
        self.pending = attributes[:'pending']
      else
        self.pending = nil
      end

      if attributes.key?(:'sent')
        self.sent = attributes[:'sent']
      else
        self.sent = nil
      end

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      else
        self.failed = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @account_status.nil?
        invalid_properties.push('invalid value for "account_status", account_status cannot be nil.')
      end

      if @pending.nil?
        invalid_properties.push('invalid value for "pending", pending cannot be nil.')
      end

      if @sent.nil?
        invalid_properties.push('invalid value for "sent", sent cannot be nil.')
      end

      if @failed.nil?
        invalid_properties.push('invalid value for "failed", failed cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @account_status.nil?
      return false if @pending.nil?
      return false if @sent.nil?
      return false if @failed.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] account_status Value to be assigned
    def account_status=(account_status)
      if account_status.nil?
        fail ArgumentError, 'account_status cannot be nil'
      end

      @account_status = account_status
    end

    # Custom attribute writer method with validation
    # @param [Object] pending Value to be assigned
    def pending=(pending)
      if pending.nil?
        fail ArgumentError, 'pending cannot be nil'
      end

      @pending = pending
    end

    # Custom attribute writer method with validation
    # @param [Object] sent Value to be assigned
    def sent=(sent)
      if sent.nil?
        fail ArgumentError, 'sent cannot be nil'
      end

      @sent = sent
    end

    # Custom attribute writer method with validation
    # @param [Object] failed Value to be assigned
    def failed=(failed)
      if failed.nil?
        fail ArgumentError, 'failed cannot be nil'
      end

      @failed = failed
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          account_status == o.account_status &&
          pending == o.pending &&
          sent == o.sent &&
          failed == o.failed
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, account_status, pending, sent, failed].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
