/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkMessageResult
 */
export interface BulkMessageResult {
    /**
     * 
     */
    recipient: string;
    /**
     * 
     */
    status: BulkMessageResultStatusEnum;
    /**
     * 
     */
    messageId?: string | null;
    /**
     * 
     */
    consentUrl?: string | null;
    /**
     * 
     */
    error?: string | null;
    /**
     * 
     */
    reason?: string | null;
}


/**
 * @export
 */
export const BulkMessageResultStatusEnum = {
    Queued: 'queued',
    ConsentRequested: 'consent_requested',
    AlreadyRequested: 'already_requested',
    AlreadyOptedIn: 'already_opted_in',
    ConsentPending: 'consent_pending',
    Rejected: 'rejected',
} as const;
export type BulkMessageResultStatusEnum = typeof BulkMessageResultStatusEnum[keyof typeof BulkMessageResultStatusEnum];


/**
 * Check if a given object implements the BulkMessageResult interface.
 */
export function instanceOfBulkMessageResult(value: object): value is BulkMessageResult {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BulkMessageResultFromJSON(json: any): BulkMessageResult {
    return BulkMessageResultFromJSONTyped(json, false);
}

export function BulkMessageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkMessageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'status': json['status'],
        'messageId': json['messageId'] === undefined ? undefined : json['messageId'] === null ? null : json['messageId'],
        'consentUrl': json['consentUrl'] === undefined ? undefined : json['consentUrl'] === null ? null : json['consentUrl'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
        'reason': json['reason'] === undefined ? undefined : json['reason'] === null ? null : json['reason'],
    };
}

export function BulkMessageResultToJSON(json: any): BulkMessageResult {
    return BulkMessageResultToJSONTyped(json, false);
}

export function BulkMessageResultToJSONTyped(value?: BulkMessageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient': value['recipient'],
        'status': value['status'],
        'messageId': value['messageId'],
        'consentUrl': value['consentUrl'],
        'error': value['error'],
        'reason': value['reason'],
    };
}

