/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkMessageRequest
 */
export interface BulkMessageRequest {
    /**
     * 
     */
    whatsappAccountId: string;
    /**
     * 
     */
    countryCode?: string;
    /**
     * 
     */
    recipients: Array<string>;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    content?: string;
    /**
     * 
     */
    mediaUrl?: string;
    /**
     * 
     */
    mediaBase64?: string;
    /**
     * 
     */
    mediaMimeType?: BulkMessageRequestMediaMimeTypeEnum;
    /**
     * 
     */
    mediaFilename?: string;
}


/**
 * @export
 */
export const BulkMessageRequestMediaMimeTypeEnum = {
    ImageJpeg: 'image/jpeg',
    ImagePng: 'image/png',
    ApplicationPdf: 'application/pdf',
} as const;
export type BulkMessageRequestMediaMimeTypeEnum = typeof BulkMessageRequestMediaMimeTypeEnum[keyof typeof BulkMessageRequestMediaMimeTypeEnum];


/**
 * Check if a given object implements the BulkMessageRequest interface.
 */
export function instanceOfBulkMessageRequest(value: object): value is BulkMessageRequest {
    if (!('whatsappAccountId' in value) || value['whatsappAccountId'] === undefined) return false;
    if (!('recipients' in value) || value['recipients'] === undefined) return false;
    return true;
}

export function BulkMessageRequestFromJSON(json: any): BulkMessageRequest {
    return BulkMessageRequestFromJSONTyped(json, false);
}

export function BulkMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'whatsappAccountId': json['whatsappAccountId'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'recipients': json['recipients'],
        'message': json['message'] == null ? undefined : json['message'],
        'content': json['content'] == null ? undefined : json['content'],
        'mediaUrl': json['mediaUrl'] == null ? undefined : json['mediaUrl'],
        'mediaBase64': json['mediaBase64'] == null ? undefined : json['mediaBase64'],
        'mediaMimeType': json['mediaMimeType'] == null ? undefined : json['mediaMimeType'],
        'mediaFilename': json['mediaFilename'] == null ? undefined : json['mediaFilename'],
    };
}

export function BulkMessageRequestToJSON(json: any): BulkMessageRequest {
    return BulkMessageRequestToJSONTyped(json, false);
}

export function BulkMessageRequestToJSONTyped(value?: BulkMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'whatsappAccountId': value['whatsappAccountId'],
        'countryCode': value['countryCode'],
        'recipients': value['recipients'],
        'message': value['message'],
        'content': value['content'],
        'mediaUrl': value['mediaUrl'],
        'mediaBase64': value['mediaBase64'],
        'mediaMimeType': value['mediaMimeType'],
        'mediaFilename': value['mediaFilename'],
    };
}

