/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectionStatus } from './ConnectionStatus';
import {
    ConnectionStatusFromJSON,
    ConnectionStatusFromJSONTyped,
    ConnectionStatusToJSON,
    ConnectionStatusToJSONTyped,
} from './ConnectionStatus';

/**
 * 
 * @export
 * @interface ConnectionStatusResponse
 */
export interface ConnectionStatusResponse {
    /**
     * 
     */
    data: ConnectionStatus;
}

/**
 * Check if a given object implements the ConnectionStatusResponse interface.
 */
export function instanceOfConnectionStatusResponse(value: object): value is ConnectionStatusResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ConnectionStatusResponseFromJSON(json: any): ConnectionStatusResponse {
    return ConnectionStatusResponseFromJSONTyped(json, false);
}

export function ConnectionStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ConnectionStatusFromJSON(json['data']),
    };
}

export function ConnectionStatusResponseToJSON(json: any): ConnectionStatusResponse {
    return ConnectionStatusResponseToJSONTyped(json, false);
}

export function ConnectionStatusResponseToJSONTyped(value?: ConnectionStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ConnectionStatusToJSON(value['data']),
    };
}

