/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionStatus
 */
export interface ConnectionStatus {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    connected: boolean;
    /**
     * 
     */
    stable: boolean;
    /**
     * 
     */
    accountStatus: string;
    /**
     * 
     */
    engineStatus: string;
    /**
     * 
     */
    sessionStatus: string;
    /**
     * 
     */
    checkedAt: Date;
}

/**
 * Check if a given object implements the ConnectionStatus interface.
 */
export function instanceOfConnectionStatus(value: object): value is ConnectionStatus {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('connected' in value) || value['connected'] === undefined) return false;
    if (!('stable' in value) || value['stable'] === undefined) return false;
    if (!('accountStatus' in value) || value['accountStatus'] === undefined) return false;
    if (!('engineStatus' in value) || value['engineStatus'] === undefined) return false;
    if (!('sessionStatus' in value) || value['sessionStatus'] === undefined) return false;
    if (!('checkedAt' in value) || value['checkedAt'] === undefined) return false;
    return true;
}

export function ConnectionStatusFromJSON(json: any): ConnectionStatus {
    return ConnectionStatusFromJSONTyped(json, false);
}

export function ConnectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'connected': json['connected'],
        'stable': json['stable'],
        'accountStatus': json['accountStatus'],
        'engineStatus': json['engineStatus'],
        'sessionStatus': json['sessionStatus'],
        'checkedAt': (json['checkedAt'] == null ? json['checkedAt'] : parseDateTime(json['checkedAt'])),
    };
}

export function ConnectionStatusToJSON(json: any): ConnectionStatus {
    return ConnectionStatusToJSONTyped(json, false);
}

export function ConnectionStatusToJSONTyped(value?: ConnectionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'connected': value['connected'],
        'stable': value['stable'],
        'accountStatus': value['accountStatus'],
        'engineStatus': value['engineStatus'],
        'sessionStatus': value['sessionStatus'],
        'checkedAt': value['checkedAt'] == null ? value['checkedAt'] : serializeDateTime(value['checkedAt']),
    };
}

