/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryStatus
 */
export interface DeliveryStatus {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    accountStatus: string;
    /**
     * QUEUED + SENDING outbound messages
     */
    pending: number;
    /**
     * 
     */
    sent: number;
    /**
     * 
     */
    failed: number;
}

/**
 * Check if a given object implements the DeliveryStatus interface.
 */
export function instanceOfDeliveryStatus(value: object): value is DeliveryStatus {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountStatus' in value) || value['accountStatus'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('sent' in value) || value['sent'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function DeliveryStatusFromJSON(json: any): DeliveryStatus {
    return DeliveryStatusFromJSONTyped(json, false);
}

export function DeliveryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountStatus': json['accountStatus'],
        'pending': json['pending'],
        'sent': json['sent'],
        'failed': json['failed'],
    };
}

export function DeliveryStatusToJSON(json: any): DeliveryStatus {
    return DeliveryStatusToJSONTyped(json, false);
}

export function DeliveryStatusToJSONTyped(value?: DeliveryStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountStatus': value['accountStatus'],
        'pending': value['pending'],
        'sent': value['sent'],
        'failed': value['failed'],
    };
}

