/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResumeDelivery } from './ResumeDelivery';
import {
    ResumeDeliveryFromJSON,
    ResumeDeliveryFromJSONTyped,
    ResumeDeliveryToJSON,
    ResumeDeliveryToJSONTyped,
} from './ResumeDelivery';

/**
 * 
 * @export
 * @interface ResumeDeliveryResponse
 */
export interface ResumeDeliveryResponse {
    /**
     * 
     */
    data: ResumeDelivery;
}

/**
 * Check if a given object implements the ResumeDeliveryResponse interface.
 */
export function instanceOfResumeDeliveryResponse(value: object): value is ResumeDeliveryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResumeDeliveryResponseFromJSON(json: any): ResumeDeliveryResponse {
    return ResumeDeliveryResponseFromJSONTyped(json, false);
}

export function ResumeDeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResumeDeliveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ResumeDeliveryFromJSON(json['data']),
    };
}

export function ResumeDeliveryResponseToJSON(json: any): ResumeDeliveryResponse {
    return ResumeDeliveryResponseToJSONTyped(json, false);
}

export function ResumeDeliveryResponseToJSONTyped(value?: ResumeDeliveryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResumeDeliveryToJSON(value['data']),
    };
}

