/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResumeDelivery
 */
export interface ResumeDelivery {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    pending: number;
    /**
     * 
     */
    requeued: number;
    /**
     * 
     */
    connected: boolean;
}

/**
 * Check if a given object implements the ResumeDelivery interface.
 */
export function instanceOfResumeDelivery(value: object): value is ResumeDelivery {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('requeued' in value) || value['requeued'] === undefined) return false;
    if (!('connected' in value) || value['connected'] === undefined) return false;
    return true;
}

export function ResumeDeliveryFromJSON(json: any): ResumeDelivery {
    return ResumeDeliveryFromJSONTyped(json, false);
}

export function ResumeDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResumeDelivery {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'pending': json['pending'],
        'requeued': json['requeued'],
        'connected': json['connected'],
    };
}

export function ResumeDeliveryToJSON(json: any): ResumeDelivery {
    return ResumeDeliveryToJSONTyped(json, false);
}

export function ResumeDeliveryToJSONTyped(value?: ResumeDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'pending': value['pending'],
        'requeued': value['requeued'],
        'connected': value['connected'],
    };
}

