/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageResponse
 */
export interface SendMessageResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    messageId: string | null;
    /**
     * 
     */
    status: SendMessageResponseStatusEnum;
    /**
     * 
     */
    consentRequired?: boolean;
    /**
     * 
     */
    consentUrl?: string | null;
    /**
     * 
     */
    message?: string;
}


/**
 * @export
 */
export const SendMessageResponseStatusEnum = {
    Queued: 'queued',
    ConsentRequested: 'consent_requested',
    ConsentPending: 'consent_pending',
    AlreadyRequested: 'already_requested',
    AlreadyOptedIn: 'already_opted_in',
} as const;
export type SendMessageResponseStatusEnum = typeof SendMessageResponseStatusEnum[keyof typeof SendMessageResponseStatusEnum];


/**
 * Check if a given object implements the SendMessageResponse interface.
 */
export function instanceOfSendMessageResponse(value: object): value is SendMessageResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SendMessageResponseFromJSON(json: any): SendMessageResponse {
    return SendMessageResponseFromJSONTyped(json, false);
}

export function SendMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'messageId': json['messageId'],
        'status': json['status'],
        'consentRequired': json['consentRequired'] == null ? undefined : json['consentRequired'],
        'consentUrl': json['consentUrl'] === undefined ? undefined : json['consentUrl'] === null ? null : json['consentUrl'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SendMessageResponseToJSON(json: any): SendMessageResponse {
    return SendMessageResponseToJSONTyped(json, false);
}

export function SendMessageResponseToJSONTyped(value?: SendMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'messageId': value['messageId'],
        'status': value['status'],
        'consentRequired': value['consentRequired'],
        'consentUrl': value['consentUrl'],
        'message': value['message'],
    };
}

