/* tslint:disable */
/* eslint-disable */
/**
 * Paygham Messaging API
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     * 
     */
    whatsappAccountId: string;
    /**
     * ISO country code; required for local numbers starting with 0
     */
    countryCode?: string;
    /**
     * Destination phone (alias: recipient)
     */
    to: string;
    /**
     * Deprecated alias for to.
     * @deprecated
     */
    recipient?: string;
    /**
     * Text body (alias: content). Optional when media is provided.
     */
    message?: string;
    /**
     * Deprecated alias for message.
     * @deprecated
     */
    content?: string;
    /**
     * Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.
     */
    mediaUrl?: string;
    /**
     * Base64-encoded media. Mutually exclusive with mediaUrl.
     */
    mediaBase64?: string;
    /**
     * Required when mediaUrl or mediaBase64 is set.
     */
    mediaMimeType?: SendMessageRequestMediaMimeTypeEnum;
    /**
     * 
     */
    mediaFilename?: string;
}


/**
 * @export
 */
export const SendMessageRequestMediaMimeTypeEnum = {
    ImageJpeg: 'image/jpeg',
    ImagePng: 'image/png',
    ApplicationPdf: 'application/pdf',
} as const;
export type SendMessageRequestMediaMimeTypeEnum = typeof SendMessageRequestMediaMimeTypeEnum[keyof typeof SendMessageRequestMediaMimeTypeEnum];


/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    if (!('whatsappAccountId' in value) || value['whatsappAccountId'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'whatsappAccountId': json['whatsappAccountId'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'to': json['to'],
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
        'message': json['message'] == null ? undefined : json['message'],
        'content': json['content'] == null ? undefined : json['content'],
        'mediaUrl': json['mediaUrl'] == null ? undefined : json['mediaUrl'],
        'mediaBase64': json['mediaBase64'] == null ? undefined : json['mediaBase64'],
        'mediaMimeType': json['mediaMimeType'] == null ? undefined : json['mediaMimeType'],
        'mediaFilename': json['mediaFilename'] == null ? undefined : json['mediaFilename'],
    };
}

export function SendMessageRequestToJSON(json: any): SendMessageRequest {
    return SendMessageRequestToJSONTyped(json, false);
}

export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'whatsappAccountId': value['whatsappAccountId'],
        'countryCode': value['countryCode'],
        'to': value['to'],
        'recipient': value['recipient'],
        'message': value['message'],
        'content': value['content'],
        'mediaUrl': value['mediaUrl'],
        'mediaBase64': value['mediaBase64'],
        'mediaMimeType': value['mediaMimeType'],
        'mediaFilename': value['mediaFilename'],
    };
}

