# coding: utf-8

"""
    Paygham Messaging API

    Public server-side API for sending WhatsApp messages and monitoring delivery.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendMessageRequest(BaseModel):
    """
    SendMessageRequest
    """ # noqa: E501
    whatsapp_account_id: StrictStr = Field(alias="whatsappAccountId")
    country_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = Field(default=None, description="ISO country code; required for local numbers starting with 0", alias="countryCode", json_schema_extra={"examples": ["AF"]})
    to: StrictStr = Field(description="Destination phone (alias: recipient)", json_schema_extra={"examples": ["0787349769"]})
    recipient: Optional[StrictStr] = Field(default=None, description="Deprecated alias for to.", json_schema_extra={"examples": ["+93787349769"]})
    message: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Text body (alias: content). Optional when media is provided.", json_schema_extra={"examples": ["Hello from my application"]})
    content: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Deprecated alias for message.")
    media_url: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.", alias="mediaUrl")
    media_base64: Optional[Annotated[str, Field(strict=True, max_length=16000000)]] = Field(default=None, description="Base64-encoded media. Mutually exclusive with mediaUrl.", alias="mediaBase64")
    media_mime_type: Optional[StrictStr] = Field(default=None, description="Required when mediaUrl or mediaBase64 is set.", alias="mediaMimeType")
    media_filename: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="mediaFilename", json_schema_extra={"examples": ["invoice.pdf"]})
    __properties: ClassVar[List[str]] = ["whatsappAccountId", "countryCode", "to", "recipient", "message", "content", "mediaUrl", "mediaBase64", "mediaMimeType", "mediaFilename"]

    @field_validator('media_url', mode="before")
    def media_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^https?:\/\/", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\//")
        return value

    @field_validator('media_mime_type')
    def media_mime_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['image/jpeg', 'image/png', 'application/pdf']):
            raise ValueError("must be one of enum values ('image/jpeg', 'image/png', 'application/pdf')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "whatsappAccountId": obj.get("whatsappAccountId"),
            "countryCode": obj.get("countryCode"),
            "to": obj.get("to"),
            "recipient": obj.get("recipient"),
            "message": obj.get("message"),
            "content": obj.get("content"),
            "mediaUrl": obj.get("mediaUrl"),
            "mediaBase64": obj.get("mediaBase64"),
            "mediaMimeType": obj.get("mediaMimeType"),
            "mediaFilename": obj.get("mediaFilename")
        })
        return _obj


