// <auto-generated>
/*
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Paygham.Client;

namespace Paygham.Model
{
    /// <summary>
    /// ApiErrorBody
    /// </summary>
    public partial class ApiErrorBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiErrorBody" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="message">message</param>
        /// <param name="details">details</param>
        [JsonConstructor]
        public ApiErrorBody(string code, string message, Option<Object> details = default)
        {
            Code = code;
            Message = message;
            DetailsOption = details;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        /* <example>VALIDATION_ERROR</example> */
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>Request validation failed</example> */
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Used to track the state of Details
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object> DetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [JsonPropertyName("details")]
        public Object Details { get { return this.DetailsOption.Value; } set { this.DetailsOption = new Option<Object>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiErrorBody {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiErrorBody" />
    /// </summary>
    public partial class ApiErrorBodyJsonConverter : JsonConverter<ApiErrorBody>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiErrorBodyJsonConverter" /> class.
        /// </summary>
        public ApiErrorBodyJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ApiErrorBody" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiErrorBody Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> code = default;
            Option<string> message = default;
            Option<Object> details = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "details":
                            details = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class ApiErrorBody.", nameof(code));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class ApiErrorBody.", nameof(message));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class ApiErrorBody.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class ApiErrorBody.");

            return new ApiErrorBody(code.Value, message.Value, details);
        }

        /// <summary>
        /// Serializes a <see cref="ApiErrorBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiErrorBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiErrorBody apiErrorBody, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiErrorBody, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiErrorBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiErrorBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiErrorBody apiErrorBody, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiErrorBody.Code == null)
                throw new ArgumentNullException(nameof(apiErrorBody.Code), "Property is required for class ApiErrorBody.");

            if (apiErrorBody.Message == null)
                throw new ArgumentNullException(nameof(apiErrorBody.Message), "Property is required for class ApiErrorBody.");

            writer.WriteString("code", apiErrorBody.Code);

            writer.WriteString("message", apiErrorBody.Message);

            if (apiErrorBody.DetailsOption.IsSet)
                if (apiErrorBody.DetailsOption.Value != null)
                {
                    writer.WritePropertyName("details");
                    JsonSerializer.Serialize(writer, apiErrorBody.Details, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("details");
        }
    }
}
