// <auto-generated>
/*
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Paygham.Client;

namespace Paygham.Model
{
    /// <summary>
    /// BulkMessageRequest
    /// </summary>
    public partial class BulkMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkMessageRequest" /> class.
        /// </summary>
        /// <param name="whatsappAccountId">whatsappAccountId</param>
        /// <param name="recipients">recipients</param>
        /// <param name="countryCode">countryCode</param>
        /// <param name="message">message</param>
        /// <param name="content">content</param>
        /// <param name="mediaUrl">mediaUrl</param>
        /// <param name="mediaBase64">mediaBase64</param>
        /// <param name="mediaMimeType">mediaMimeType</param>
        /// <param name="mediaFilename">mediaFilename</param>
        [JsonConstructor]
        public BulkMessageRequest(string whatsappAccountId, List<string> recipients, Option<string> countryCode = default, Option<string> message = default, Option<string> content = default, Option<string> mediaUrl = default, Option<string> mediaBase64 = default, Option<MediaMimeTypeEnum?> mediaMimeType = default, Option<string> mediaFilename = default)
        {
            WhatsappAccountId = whatsappAccountId;
            Recipients = recipients;
            CountryCodeOption = countryCode;
            MessageOption = message;
            ContentOption = content;
            MediaUrlOption = mediaUrl;
            MediaBase64Option = mediaBase64;
            MediaMimeTypeOption = mediaMimeType;
            MediaFilenameOption = mediaFilename;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines MediaMimeType
        /// </summary>
        public enum MediaMimeTypeEnum
        {
            /// <summary>
            /// Enum ImageJpeg for value: image/jpeg
            /// </summary>
            ImageJpeg = 1,

            /// <summary>
            /// Enum ImagePng for value: image/png
            /// </summary>
            ImagePng = 2,

            /// <summary>
            /// Enum ApplicationPdf for value: application/pdf
            /// </summary>
            ApplicationPdf = 3
        }

        /// <summary>
        /// Returns a <see cref="MediaMimeTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MediaMimeTypeEnum MediaMimeTypeEnumFromString(string value)
        {
            if (value.Equals("image/jpeg"))
                return MediaMimeTypeEnum.ImageJpeg;

            if (value.Equals("image/png"))
                return MediaMimeTypeEnum.ImagePng;

            if (value.Equals("application/pdf"))
                return MediaMimeTypeEnum.ApplicationPdf;

            throw new NotImplementedException($"Could not convert value to type MediaMimeTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MediaMimeTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MediaMimeTypeEnum? MediaMimeTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("image/jpeg"))
                return MediaMimeTypeEnum.ImageJpeg;

            if (value.Equals("image/png"))
                return MediaMimeTypeEnum.ImagePng;

            if (value.Equals("application/pdf"))
                return MediaMimeTypeEnum.ApplicationPdf;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MediaMimeTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MediaMimeTypeEnumToJsonValue(MediaMimeTypeEnum? value)
        {
            if (value == MediaMimeTypeEnum.ImageJpeg)
                return "image/jpeg";

            if (value == MediaMimeTypeEnum.ImagePng)
                return "image/png";

            if (value == MediaMimeTypeEnum.ApplicationPdf)
                return "application/pdf";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of MediaMimeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MediaMimeTypeEnum?> MediaMimeTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MediaMimeType
        /// </summary>
        [JsonPropertyName("mediaMimeType")]
        public MediaMimeTypeEnum? MediaMimeType { get { return this.MediaMimeTypeOption.Value; } set { this.MediaMimeTypeOption = new Option<MediaMimeTypeEnum?>(value); } }

        /// <summary>
        /// Gets or Sets WhatsappAccountId
        /// </summary>
        [JsonPropertyName("whatsappAccountId")]
        public string WhatsappAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        /* <example>[&quot;0787349769&quot;,&quot;+93787349770&quot;]</example> */
        [JsonPropertyName("recipients")]
        public List<string> Recipients { get; set; }

        /// <summary>
        /// Used to track the state of CountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CountryCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        /* <example>AF</example> */
        [JsonPropertyName("countryCode")]
        public string CountryCode { get { return this.CountryCodeOption.Value; } set { this.CountryCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ContentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [JsonPropertyName("content")]
        public string Content { get { return this.ContentOption.Value; } set { this.ContentOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets MediaUrl
        /// </summary>
        [JsonPropertyName("mediaUrl")]
        public string MediaUrl { get { return this.MediaUrlOption.Value; } set { this.MediaUrlOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaBase64
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaBase64Option { get; private set; }

        /// <summary>
        /// Gets or Sets MediaBase64
        /// </summary>
        [JsonPropertyName("mediaBase64")]
        public string MediaBase64 { get { return this.MediaBase64Option.Value; } set { this.MediaBase64Option = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaFilename
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaFilenameOption { get; private set; }

        /// <summary>
        /// Gets or Sets MediaFilename
        /// </summary>
        [JsonPropertyName("mediaFilename")]
        public string MediaFilename { get { return this.MediaFilenameOption.Value; } set { this.MediaFilenameOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkMessageRequest {\n");
            sb.Append("  WhatsappAccountId: ").Append(WhatsappAccountId).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  MediaUrl: ").Append(MediaUrl).Append("\n");
            sb.Append("  MediaBase64: ").Append(MediaBase64).Append("\n");
            sb.Append("  MediaMimeType: ").Append(MediaMimeType).Append("\n");
            sb.Append("  MediaFilename: ").Append(MediaFilename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CountryCode (string) maxLength
            if (this.CountryCode != null && this.CountryCode.Length > 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be less than 2.", new [] { "CountryCode" });
            }

            // CountryCode (string) minLength
            if (this.CountryCode != null && this.CountryCode.Length < 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be greater than 2.", new [] { "CountryCode" });
            }

            // Message (string) maxLength
            if (this.Message != null && this.Message.Length > 4096)
            {
                yield return new ValidationResult("Invalid value for Message, length must be less than 4096.", new [] { "Message" });
            }

            // Content (string) maxLength
            if (this.Content != null && this.Content.Length > 4096)
            {
                yield return new ValidationResult("Invalid value for Content, length must be less than 4096.", new [] { "Content" });
            }

            if (this.MediaUrlOption.Value != null) {
                // MediaUrl (string) pattern
                Regex regexMediaUrl = new Regex(@"^https?://", RegexOptions.CultureInvariant);

                if (this.MediaUrlOption.Value != null &&!regexMediaUrl.Match(this.MediaUrlOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MediaUrl, must match a pattern of " + regexMediaUrl, new [] { "MediaUrl" });
                }
            }

            // MediaBase64 (string) maxLength
            if (this.MediaBase64 != null && this.MediaBase64.Length > 16000000)
            {
                yield return new ValidationResult("Invalid value for MediaBase64, length must be less than 16000000.", new [] { "MediaBase64" });
            }

            // MediaFilename (string) maxLength
            if (this.MediaFilename != null && this.MediaFilename.Length > 255)
            {
                yield return new ValidationResult("Invalid value for MediaFilename, length must be less than 255.", new [] { "MediaFilename" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkMessageRequest" />
    /// </summary>
    public partial class BulkMessageRequestJsonConverter : JsonConverter<BulkMessageRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BulkMessageRequestJsonConverter" /> class.
        /// </summary>
        public BulkMessageRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BulkMessageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkMessageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> whatsappAccountId = default;
            Option<List<string>> recipients = default;
            Option<string> countryCode = default;
            Option<string> message = default;
            Option<string> content = default;
            Option<string> mediaUrl = default;
            Option<string> mediaBase64 = default;
            Option<BulkMessageRequest.MediaMimeTypeEnum?> mediaMimeType = default;
            Option<string> mediaFilename = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "whatsappAccountId":
                            whatsappAccountId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "recipients":
                            recipients = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "countryCode":
                            countryCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "content":
                            content = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaUrl":
                            mediaUrl = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaBase64":
                            mediaBase64 = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaMimeType":
                            string mediaMimeTypeRawValue = utf8JsonReader.GetString();
                            if (mediaMimeTypeRawValue != null)
                            {
                                BulkMessageRequest.MediaMimeTypeEnum? mediaMimeTypeValue = BulkMessageRequest.MediaMimeTypeEnumFromStringOrDefault(mediaMimeTypeRawValue);
                                if (mediaMimeTypeValue == null)
                                    throw new JsonException();
                                mediaMimeType = new Option<BulkMessageRequest.MediaMimeTypeEnum?>(mediaMimeTypeValue);
                            }
                            break;
                        case "mediaFilename":
                            mediaFilename = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!whatsappAccountId.IsSet)
                throw new ArgumentException("Property is required for class BulkMessageRequest.", nameof(whatsappAccountId));

            if (!recipients.IsSet)
                throw new ArgumentException("Property is required for class BulkMessageRequest.", nameof(recipients));

            if (whatsappAccountId.IsSet && whatsappAccountId.Value == null)
                throw new ArgumentNullException(nameof(whatsappAccountId), "Property is not nullable for class BulkMessageRequest.");

            if (recipients.IsSet && recipients.Value == null)
                throw new ArgumentNullException(nameof(recipients), "Property is not nullable for class BulkMessageRequest.");

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class BulkMessageRequest.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class BulkMessageRequest.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class BulkMessageRequest.");

            if (mediaUrl.IsSet && mediaUrl.Value == null)
                throw new ArgumentNullException(nameof(mediaUrl), "Property is not nullable for class BulkMessageRequest.");

            if (mediaBase64.IsSet && mediaBase64.Value == null)
                throw new ArgumentNullException(nameof(mediaBase64), "Property is not nullable for class BulkMessageRequest.");

            if (mediaMimeType.IsSet && mediaMimeType.Value == null)
                throw new ArgumentNullException(nameof(mediaMimeType), "Property is not nullable for class BulkMessageRequest.");

            if (mediaFilename.IsSet && mediaFilename.Value == null)
                throw new ArgumentNullException(nameof(mediaFilename), "Property is not nullable for class BulkMessageRequest.");

            return new BulkMessageRequest(whatsappAccountId.Value, recipients.Value, countryCode, message, content, mediaUrl, mediaBase64, mediaMimeType, mediaFilename);
        }

        /// <summary>
        /// Serializes a <see cref="BulkMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkMessageRequest bulkMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkMessageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkMessageRequest bulkMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkMessageRequest.WhatsappAccountId == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.WhatsappAccountId), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.Recipients == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.Recipients), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.CountryCodeOption.IsSet && bulkMessageRequest.CountryCode == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.CountryCode), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.MessageOption.IsSet && bulkMessageRequest.Message == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.Message), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.ContentOption.IsSet && bulkMessageRequest.Content == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.Content), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.MediaUrlOption.IsSet && bulkMessageRequest.MediaUrl == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.MediaUrl), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.MediaBase64Option.IsSet && bulkMessageRequest.MediaBase64 == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.MediaBase64), "Property is required for class BulkMessageRequest.");

            if (bulkMessageRequest.MediaFilenameOption.IsSet && bulkMessageRequest.MediaFilename == null)
                throw new ArgumentNullException(nameof(bulkMessageRequest.MediaFilename), "Property is required for class BulkMessageRequest.");

            writer.WriteString("whatsappAccountId", bulkMessageRequest.WhatsappAccountId);

            writer.WritePropertyName("recipients");
            JsonSerializer.Serialize(writer, bulkMessageRequest.Recipients, jsonSerializerOptions);
            if (bulkMessageRequest.CountryCodeOption.IsSet)
                writer.WriteString("countryCode", bulkMessageRequest.CountryCode);

            if (bulkMessageRequest.MessageOption.IsSet)
                writer.WriteString("message", bulkMessageRequest.Message);

            if (bulkMessageRequest.ContentOption.IsSet)
                writer.WriteString("content", bulkMessageRequest.Content);

            if (bulkMessageRequest.MediaUrlOption.IsSet)
                writer.WriteString("mediaUrl", bulkMessageRequest.MediaUrl);

            if (bulkMessageRequest.MediaBase64Option.IsSet)
                writer.WriteString("mediaBase64", bulkMessageRequest.MediaBase64);

            var mediaMimeTypeRawValue = BulkMessageRequest.MediaMimeTypeEnumToJsonValue(bulkMessageRequest.MediaMimeTypeOption.Value.Value);
            writer.WriteString("mediaMimeType", mediaMimeTypeRawValue);
            if (bulkMessageRequest.MediaFilenameOption.IsSet)
                writer.WriteString("mediaFilename", bulkMessageRequest.MediaFilename);
        }
    }
}
