// <auto-generated>
/*
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Paygham.Client;

namespace Paygham.Model
{
    /// <summary>
    /// ConnectionStatus
    /// </summary>
    public partial class ConnectionStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionStatus" /> class.
        /// </summary>
        /// <param name="accountId">accountId</param>
        /// <param name="connected">connected</param>
        /// <param name="stable">stable</param>
        /// <param name="accountStatus">accountStatus</param>
        /// <param name="engineStatus">engineStatus</param>
        /// <param name="sessionStatus">sessionStatus</param>
        /// <param name="checkedAt">checkedAt</param>
        [JsonConstructor]
        public ConnectionStatus(string accountId, bool connected, bool stable, string accountStatus, string engineStatus, string sessionStatus, DateTime checkedAt)
        {
            AccountId = accountId;
            Connected = connected;
            Stable = stable;
            AccountStatus = accountStatus;
            EngineStatus = engineStatus;
            SessionStatus = sessionStatus;
            CheckedAt = checkedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [JsonPropertyName("accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets Connected
        /// </summary>
        [JsonPropertyName("connected")]
        public bool Connected { get; set; }

        /// <summary>
        /// Gets or Sets Stable
        /// </summary>
        [JsonPropertyName("stable")]
        public bool Stable { get; set; }

        /// <summary>
        /// Gets or Sets AccountStatus
        /// </summary>
        [JsonPropertyName("accountStatus")]
        public string AccountStatus { get; set; }

        /// <summary>
        /// Gets or Sets EngineStatus
        /// </summary>
        [JsonPropertyName("engineStatus")]
        public string EngineStatus { get; set; }

        /// <summary>
        /// Gets or Sets SessionStatus
        /// </summary>
        [JsonPropertyName("sessionStatus")]
        public string SessionStatus { get; set; }

        /// <summary>
        /// Gets or Sets CheckedAt
        /// </summary>
        [JsonPropertyName("checkedAt")]
        public DateTime CheckedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionStatus {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Connected: ").Append(Connected).Append("\n");
            sb.Append("  Stable: ").Append(Stable).Append("\n");
            sb.Append("  AccountStatus: ").Append(AccountStatus).Append("\n");
            sb.Append("  EngineStatus: ").Append(EngineStatus).Append("\n");
            sb.Append("  SessionStatus: ").Append(SessionStatus).Append("\n");
            sb.Append("  CheckedAt: ").Append(CheckedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConnectionStatus" />
    /// </summary>
    public partial class ConnectionStatusJsonConverter : JsonConverter<ConnectionStatus>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionStatusJsonConverter" /> class.
        /// </summary>
        public ConnectionStatusJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CheckedAt
        /// </summary>
        public string CheckedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ConnectionStatus" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConnectionStatus Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> accountId = default;
            Option<bool?> connected = default;
            Option<bool?> stable = default;
            Option<string> accountStatus = default;
            Option<string> engineStatus = default;
            Option<string> sessionStatus = default;
            Option<DateTime?> checkedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "accountId":
                            accountId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "connected":
                            connected = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "stable":
                            stable = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "accountStatus":
                            accountStatus = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "engineStatus":
                            engineStatus = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "sessionStatus":
                            sessionStatus = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "checkedAt":
                            checkedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!accountId.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(accountId));

            if (!connected.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(connected));

            if (!stable.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(stable));

            if (!accountStatus.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(accountStatus));

            if (!engineStatus.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(engineStatus));

            if (!sessionStatus.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(sessionStatus));

            if (!checkedAt.IsSet)
                throw new ArgumentException("Property is required for class ConnectionStatus.", nameof(checkedAt));

            if (accountId.IsSet && accountId.Value == null)
                throw new ArgumentNullException(nameof(accountId), "Property is not nullable for class ConnectionStatus.");

            if (connected.IsSet && connected.Value == null)
                throw new ArgumentNullException(nameof(connected), "Property is not nullable for class ConnectionStatus.");

            if (stable.IsSet && stable.Value == null)
                throw new ArgumentNullException(nameof(stable), "Property is not nullable for class ConnectionStatus.");

            if (accountStatus.IsSet && accountStatus.Value == null)
                throw new ArgumentNullException(nameof(accountStatus), "Property is not nullable for class ConnectionStatus.");

            if (engineStatus.IsSet && engineStatus.Value == null)
                throw new ArgumentNullException(nameof(engineStatus), "Property is not nullable for class ConnectionStatus.");

            if (sessionStatus.IsSet && sessionStatus.Value == null)
                throw new ArgumentNullException(nameof(sessionStatus), "Property is not nullable for class ConnectionStatus.");

            if (checkedAt.IsSet && checkedAt.Value == null)
                throw new ArgumentNullException(nameof(checkedAt), "Property is not nullable for class ConnectionStatus.");

            return new ConnectionStatus(accountId.Value, connected.Value.Value, stable.Value.Value, accountStatus.Value, engineStatus.Value, sessionStatus.Value, checkedAt.Value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ConnectionStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConnectionStatus connectionStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, connectionStatus, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConnectionStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConnectionStatus connectionStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            if (connectionStatus.AccountId == null)
                throw new ArgumentNullException(nameof(connectionStatus.AccountId), "Property is required for class ConnectionStatus.");

            if (connectionStatus.AccountStatus == null)
                throw new ArgumentNullException(nameof(connectionStatus.AccountStatus), "Property is required for class ConnectionStatus.");

            if (connectionStatus.EngineStatus == null)
                throw new ArgumentNullException(nameof(connectionStatus.EngineStatus), "Property is required for class ConnectionStatus.");

            if (connectionStatus.SessionStatus == null)
                throw new ArgumentNullException(nameof(connectionStatus.SessionStatus), "Property is required for class ConnectionStatus.");

            writer.WriteString("accountId", connectionStatus.AccountId);

            writer.WriteBoolean("connected", connectionStatus.Connected);

            writer.WriteBoolean("stable", connectionStatus.Stable);

            writer.WriteString("accountStatus", connectionStatus.AccountStatus);

            writer.WriteString("engineStatus", connectionStatus.EngineStatus);

            writer.WriteString("sessionStatus", connectionStatus.SessionStatus);

            writer.WriteString("checkedAt", connectionStatus.CheckedAt.ToString(CheckedAtFormat));
        }
    }
}
