// <auto-generated>
/*
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Paygham.Client;

namespace Paygham.Model
{
    /// <summary>
    /// ResumeDeliveryResponse
    /// </summary>
    public partial class ResumeDeliveryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResumeDeliveryResponse" /> class.
        /// </summary>
        /// <param name="data">data</param>
        [JsonConstructor]
        public ResumeDeliveryResponse(ResumeDelivery data)
        {
            Data = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public ResumeDelivery Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResumeDeliveryResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResumeDeliveryResponse" />
    /// </summary>
    public partial class ResumeDeliveryResponseJsonConverter : JsonConverter<ResumeDeliveryResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ResumeDeliveryResponseJsonConverter" /> class.
        /// </summary>
        public ResumeDeliveryResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ResumeDeliveryResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ResumeDeliveryResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ResumeDelivery> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<ResumeDelivery>(JsonSerializer.Deserialize<ResumeDelivery>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class ResumeDeliveryResponse.", nameof(data));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class ResumeDeliveryResponse.");

            return new ResumeDeliveryResponse(data.Value);
        }

        /// <summary>
        /// Serializes a <see cref="ResumeDeliveryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resumeDeliveryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ResumeDeliveryResponse resumeDeliveryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, resumeDeliveryResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ResumeDeliveryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resumeDeliveryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ResumeDeliveryResponse resumeDeliveryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (resumeDeliveryResponse.Data == null)
                throw new ArgumentNullException(nameof(resumeDeliveryResponse.Data), "Property is required for class ResumeDeliveryResponse.");

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, resumeDeliveryResponse.Data, jsonSerializerOptions);
        }
    }
}
