// <auto-generated>
/*
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Paygham.Client;

namespace Paygham.Model
{
    /// <summary>
    /// SendMessageRequest
    /// </summary>
    public partial class SendMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessageRequest" /> class.
        /// </summary>
        /// <param name="whatsappAccountId">whatsappAccountId</param>
        /// <param name="to">Destination phone (alias: recipient)</param>
        /// <param name="countryCode">ISO country code; required for local numbers starting with 0</param>
        /// <param name="recipient">Deprecated alias for to.</param>
        /// <param name="message">Text body (alias: content). Optional when media is provided.</param>
        /// <param name="content">Deprecated alias for message.</param>
        /// <param name="mediaUrl">Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.</param>
        /// <param name="mediaBase64">Base64-encoded media. Mutually exclusive with mediaUrl.</param>
        /// <param name="mediaMimeType">Required when mediaUrl or mediaBase64 is set.</param>
        /// <param name="mediaFilename">mediaFilename</param>
        [JsonConstructor]
        public SendMessageRequest(string whatsappAccountId, string to, Option<string> countryCode = default, Option<string> recipient = default, Option<string> message = default, Option<string> content = default, Option<string> mediaUrl = default, Option<string> mediaBase64 = default, Option<MediaMimeTypeEnum?> mediaMimeType = default, Option<string> mediaFilename = default)
        {
            WhatsappAccountId = whatsappAccountId;
            To = to;
            CountryCodeOption = countryCode;
            RecipientOption = recipient;
            MessageOption = message;
            ContentOption = content;
            MediaUrlOption = mediaUrl;
            MediaBase64Option = mediaBase64;
            MediaMimeTypeOption = mediaMimeType;
            MediaFilenameOption = mediaFilename;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Required when mediaUrl or mediaBase64 is set.
        /// </summary>
        /// <value>Required when mediaUrl or mediaBase64 is set.</value>
        public enum MediaMimeTypeEnum
        {
            /// <summary>
            /// Enum ImageJpeg for value: image/jpeg
            /// </summary>
            ImageJpeg = 1,

            /// <summary>
            /// Enum ImagePng for value: image/png
            /// </summary>
            ImagePng = 2,

            /// <summary>
            /// Enum ApplicationPdf for value: application/pdf
            /// </summary>
            ApplicationPdf = 3
        }

        /// <summary>
        /// Returns a <see cref="MediaMimeTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MediaMimeTypeEnum MediaMimeTypeEnumFromString(string value)
        {
            if (value.Equals("image/jpeg"))
                return MediaMimeTypeEnum.ImageJpeg;

            if (value.Equals("image/png"))
                return MediaMimeTypeEnum.ImagePng;

            if (value.Equals("application/pdf"))
                return MediaMimeTypeEnum.ApplicationPdf;

            throw new NotImplementedException($"Could not convert value to type MediaMimeTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MediaMimeTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MediaMimeTypeEnum? MediaMimeTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("image/jpeg"))
                return MediaMimeTypeEnum.ImageJpeg;

            if (value.Equals("image/png"))
                return MediaMimeTypeEnum.ImagePng;

            if (value.Equals("application/pdf"))
                return MediaMimeTypeEnum.ApplicationPdf;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MediaMimeTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MediaMimeTypeEnumToJsonValue(MediaMimeTypeEnum? value)
        {
            if (value == MediaMimeTypeEnum.ImageJpeg)
                return "image/jpeg";

            if (value == MediaMimeTypeEnum.ImagePng)
                return "image/png";

            if (value == MediaMimeTypeEnum.ApplicationPdf)
                return "application/pdf";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of MediaMimeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MediaMimeTypeEnum?> MediaMimeTypeOption { get; private set; }

        /// <summary>
        /// Required when mediaUrl or mediaBase64 is set.
        /// </summary>
        /// <value>Required when mediaUrl or mediaBase64 is set.</value>
        [JsonPropertyName("mediaMimeType")]
        public MediaMimeTypeEnum? MediaMimeType { get { return this.MediaMimeTypeOption.Value; } set { this.MediaMimeTypeOption = new Option<MediaMimeTypeEnum?>(value); } }

        /// <summary>
        /// Gets or Sets WhatsappAccountId
        /// </summary>
        [JsonPropertyName("whatsappAccountId")]
        public string WhatsappAccountId { get; set; }

        /// <summary>
        /// Destination phone (alias: recipient)
        /// </summary>
        /// <value>Destination phone (alias: recipient)</value>
        /* <example>0787349769</example> */
        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        /// Used to track the state of CountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CountryCodeOption { get; private set; }

        /// <summary>
        /// ISO country code; required for local numbers starting with 0
        /// </summary>
        /// <value>ISO country code; required for local numbers starting with 0</value>
        /* <example>AF</example> */
        [JsonPropertyName("countryCode")]
        public string CountryCode { get { return this.CountryCodeOption.Value; } set { this.CountryCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Recipient
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RecipientOption { get; private set; }

        /// <summary>
        /// Deprecated alias for to.
        /// </summary>
        /// <value>Deprecated alias for to.</value>
        /* <example>+93787349769</example> */
        [JsonPropertyName("recipient")]
        [Obsolete]
        public string Recipient { get { return this.RecipientOption.Value; } set { this.RecipientOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MessageOption { get; private set; }

        /// <summary>
        /// Text body (alias: content). Optional when media is provided.
        /// </summary>
        /// <value>Text body (alias: content). Optional when media is provided.</value>
        /* <example>Hello from my application</example> */
        [JsonPropertyName("message")]
        public string Message { get { return this.MessageOption.Value; } set { this.MessageOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ContentOption { get; private set; }

        /// <summary>
        /// Deprecated alias for message.
        /// </summary>
        /// <value>Deprecated alias for message.</value>
        [JsonPropertyName("content")]
        [Obsolete]
        public string Content { get { return this.ContentOption.Value; } set { this.ContentOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaUrlOption { get; private set; }

        /// <summary>
        /// Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.
        /// </summary>
        /// <value>Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.</value>
        [JsonPropertyName("mediaUrl")]
        public string MediaUrl { get { return this.MediaUrlOption.Value; } set { this.MediaUrlOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaBase64
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaBase64Option { get; private set; }

        /// <summary>
        /// Base64-encoded media. Mutually exclusive with mediaUrl.
        /// </summary>
        /// <value>Base64-encoded media. Mutually exclusive with mediaUrl.</value>
        [JsonPropertyName("mediaBase64")]
        public string MediaBase64 { get { return this.MediaBase64Option.Value; } set { this.MediaBase64Option = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of MediaFilename
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MediaFilenameOption { get; private set; }

        /// <summary>
        /// Gets or Sets MediaFilename
        /// </summary>
        /* <example>invoice.pdf</example> */
        [JsonPropertyName("mediaFilename")]
        public string MediaFilename { get { return this.MediaFilenameOption.Value; } set { this.MediaFilenameOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendMessageRequest {\n");
            sb.Append("  WhatsappAccountId: ").Append(WhatsappAccountId).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  MediaUrl: ").Append(MediaUrl).Append("\n");
            sb.Append("  MediaBase64: ").Append(MediaBase64).Append("\n");
            sb.Append("  MediaMimeType: ").Append(MediaMimeType).Append("\n");
            sb.Append("  MediaFilename: ").Append(MediaFilename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CountryCode (string) maxLength
            if (this.CountryCode != null && this.CountryCode.Length > 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be less than 2.", new [] { "CountryCode" });
            }

            // CountryCode (string) minLength
            if (this.CountryCode != null && this.CountryCode.Length < 2)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be greater than 2.", new [] { "CountryCode" });
            }

            // Message (string) maxLength
            if (this.Message != null && this.Message.Length > 4096)
            {
                yield return new ValidationResult("Invalid value for Message, length must be less than 4096.", new [] { "Message" });
            }

            // Content (string) maxLength
            if (this.Content != null && this.Content.Length > 4096)
            {
                yield return new ValidationResult("Invalid value for Content, length must be less than 4096.", new [] { "Content" });
            }

            if (this.MediaUrlOption.Value != null) {
                // MediaUrl (string) pattern
                Regex regexMediaUrl = new Regex(@"^https?://", RegexOptions.CultureInvariant);

                if (this.MediaUrlOption.Value != null &&!regexMediaUrl.Match(this.MediaUrlOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MediaUrl, must match a pattern of " + regexMediaUrl, new [] { "MediaUrl" });
                }
            }

            // MediaBase64 (string) maxLength
            if (this.MediaBase64 != null && this.MediaBase64.Length > 16000000)
            {
                yield return new ValidationResult("Invalid value for MediaBase64, length must be less than 16000000.", new [] { "MediaBase64" });
            }

            // MediaFilename (string) maxLength
            if (this.MediaFilename != null && this.MediaFilename.Length > 255)
            {
                yield return new ValidationResult("Invalid value for MediaFilename, length must be less than 255.", new [] { "MediaFilename" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendMessageRequest" />
    /// </summary>
    public partial class SendMessageRequestJsonConverter : JsonConverter<SendMessageRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessageRequestJsonConverter" /> class.
        /// </summary>
        public SendMessageRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendMessageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> whatsappAccountId = default;
            Option<string> to = default;
            Option<string> countryCode = default;
            Option<string> recipient = default;
            Option<string> message = default;
            Option<string> content = default;
            Option<string> mediaUrl = default;
            Option<string> mediaBase64 = default;
            Option<SendMessageRequest.MediaMimeTypeEnum?> mediaMimeType = default;
            Option<string> mediaFilename = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "whatsappAccountId":
                            whatsappAccountId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "to":
                            to = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "countryCode":
                            countryCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "recipient":
                            recipient = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "content":
                            content = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaUrl":
                            mediaUrl = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaBase64":
                            mediaBase64 = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "mediaMimeType":
                            string mediaMimeTypeRawValue = utf8JsonReader.GetString();
                            if (mediaMimeTypeRawValue != null)
                            {
                                SendMessageRequest.MediaMimeTypeEnum? mediaMimeTypeValue = SendMessageRequest.MediaMimeTypeEnumFromStringOrDefault(mediaMimeTypeRawValue);
                                if (mediaMimeTypeValue == null)
                                    throw new JsonException();
                                mediaMimeType = new Option<SendMessageRequest.MediaMimeTypeEnum?>(mediaMimeTypeValue);
                            }
                            break;
                        case "mediaFilename":
                            mediaFilename = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!whatsappAccountId.IsSet)
                throw new ArgumentException("Property is required for class SendMessageRequest.", nameof(whatsappAccountId));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class SendMessageRequest.", nameof(to));

            if (whatsappAccountId.IsSet && whatsappAccountId.Value == null)
                throw new ArgumentNullException(nameof(whatsappAccountId), "Property is not nullable for class SendMessageRequest.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class SendMessageRequest.");

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode), "Property is not nullable for class SendMessageRequest.");

            if (recipient.IsSet && recipient.Value == null)
                throw new ArgumentNullException(nameof(recipient), "Property is not nullable for class SendMessageRequest.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class SendMessageRequest.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class SendMessageRequest.");

            if (mediaUrl.IsSet && mediaUrl.Value == null)
                throw new ArgumentNullException(nameof(mediaUrl), "Property is not nullable for class SendMessageRequest.");

            if (mediaBase64.IsSet && mediaBase64.Value == null)
                throw new ArgumentNullException(nameof(mediaBase64), "Property is not nullable for class SendMessageRequest.");

            if (mediaMimeType.IsSet && mediaMimeType.Value == null)
                throw new ArgumentNullException(nameof(mediaMimeType), "Property is not nullable for class SendMessageRequest.");

            if (mediaFilename.IsSet && mediaFilename.Value == null)
                throw new ArgumentNullException(nameof(mediaFilename), "Property is not nullable for class SendMessageRequest.");

            return new SendMessageRequest(whatsappAccountId.Value, to.Value, countryCode, recipient, message, content, mediaUrl, mediaBase64, mediaMimeType, mediaFilename);
        }

        /// <summary>
        /// Serializes a <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendMessageRequest sendMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendMessageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendMessageRequest sendMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendMessageRequest.WhatsappAccountId == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.WhatsappAccountId), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.To == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.To), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.CountryCodeOption.IsSet && sendMessageRequest.CountryCode == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.CountryCode), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.RecipientOption.IsSet && sendMessageRequest.Recipient == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.Recipient), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.MessageOption.IsSet && sendMessageRequest.Message == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.Message), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.ContentOption.IsSet && sendMessageRequest.Content == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.Content), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.MediaUrlOption.IsSet && sendMessageRequest.MediaUrl == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.MediaUrl), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.MediaBase64Option.IsSet && sendMessageRequest.MediaBase64 == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.MediaBase64), "Property is required for class SendMessageRequest.");

            if (sendMessageRequest.MediaFilenameOption.IsSet && sendMessageRequest.MediaFilename == null)
                throw new ArgumentNullException(nameof(sendMessageRequest.MediaFilename), "Property is required for class SendMessageRequest.");

            writer.WriteString("whatsappAccountId", sendMessageRequest.WhatsappAccountId);

            writer.WriteString("to", sendMessageRequest.To);

            if (sendMessageRequest.CountryCodeOption.IsSet)
                writer.WriteString("countryCode", sendMessageRequest.CountryCode);

            if (sendMessageRequest.RecipientOption.IsSet)
                writer.WriteString("recipient", sendMessageRequest.Recipient);

            if (sendMessageRequest.MessageOption.IsSet)
                writer.WriteString("message", sendMessageRequest.Message);

            if (sendMessageRequest.ContentOption.IsSet)
                writer.WriteString("content", sendMessageRequest.Content);

            if (sendMessageRequest.MediaUrlOption.IsSet)
                writer.WriteString("mediaUrl", sendMessageRequest.MediaUrl);

            if (sendMessageRequest.MediaBase64Option.IsSet)
                writer.WriteString("mediaBase64", sendMessageRequest.MediaBase64);

            var mediaMimeTypeRawValue = SendMessageRequest.MediaMimeTypeEnumToJsonValue(sendMessageRequest.MediaMimeTypeOption.Value.Value);
            writer.WriteString("mediaMimeType", mediaMimeTypeRawValue);
            if (sendMessageRequest.MediaFilenameOption.IsSet)
                writer.WriteString("mediaFilename", sendMessageRequest.MediaFilename);
        }
    }
}
