<?php
/**
 * BulkMessageRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Paygham
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Paygham\Model;

use \ArrayAccess;
use \Paygham\ObjectSerializer;

/**
 * BulkMessageRequest Class Doc Comment
 *
 * @category Class
 * @package  Paygham
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BulkMessageRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'BulkMessageRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'whatsapp_account_id' => 'string',
        'country_code' => 'string',
        'recipients' => 'string[]',
        'message' => 'string',
        'content' => 'string',
        'media_url' => 'string',
        'media_base64' => 'string',
        'media_mime_type' => 'string',
        'media_filename' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'whatsapp_account_id' => null,
        'country_code' => null,
        'recipients' => null,
        'message' => null,
        'content' => null,
        'media_url' => 'uri',
        'media_base64' => null,
        'media_mime_type' => null,
        'media_filename' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'whatsapp_account_id' => false,
        'country_code' => false,
        'recipients' => false,
        'message' => false,
        'content' => false,
        'media_url' => false,
        'media_base64' => false,
        'media_mime_type' => false,
        'media_filename' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'whatsapp_account_id' => 'whatsappAccountId',
        'country_code' => 'countryCode',
        'recipients' => 'recipients',
        'message' => 'message',
        'content' => 'content',
        'media_url' => 'mediaUrl',
        'media_base64' => 'mediaBase64',
        'media_mime_type' => 'mediaMimeType',
        'media_filename' => 'mediaFilename'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'whatsapp_account_id' => 'setWhatsappAccountId',
        'country_code' => 'setCountryCode',
        'recipients' => 'setRecipients',
        'message' => 'setMessage',
        'content' => 'setContent',
        'media_url' => 'setMediaUrl',
        'media_base64' => 'setMediaBase64',
        'media_mime_type' => 'setMediaMimeType',
        'media_filename' => 'setMediaFilename'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'whatsapp_account_id' => 'getWhatsappAccountId',
        'country_code' => 'getCountryCode',
        'recipients' => 'getRecipients',
        'message' => 'getMessage',
        'content' => 'getContent',
        'media_url' => 'getMediaUrl',
        'media_base64' => 'getMediaBase64',
        'media_mime_type' => 'getMediaMimeType',
        'media_filename' => 'getMediaFilename'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const MEDIA_MIME_TYPE_IMAGE_JPEG = 'image/jpeg';
    public const MEDIA_MIME_TYPE_IMAGE_PNG = 'image/png';
    public const MEDIA_MIME_TYPE_APPLICATION_PDF = 'application/pdf';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMediaMimeTypeAllowableValues()
    {
        return [
            self::MEDIA_MIME_TYPE_IMAGE_JPEG,
            self::MEDIA_MIME_TYPE_IMAGE_PNG,
            self::MEDIA_MIME_TYPE_APPLICATION_PDF,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('whatsapp_account_id', $data ?? [], null);
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('media_url', $data ?? [], null);
        $this->setIfExists('media_base64', $data ?? [], null);
        $this->setIfExists('media_mime_type', $data ?? [], null);
        $this->setIfExists('media_filename', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['whatsapp_account_id'] === null) {
            $invalidProperties[] = "'whatsapp_account_id' can't be null";
        }
        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) > 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) < 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if ((count($this->container['recipients']) < 1)) {
            $invalidProperties[] = "invalid value for 'recipients', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['message']) && (mb_strlen($this->container['message']) > 4096)) {
            $invalidProperties[] = "invalid value for 'message', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['content']) && (mb_strlen($this->container['content']) > 4096)) {
            $invalidProperties[] = "invalid value for 'content', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['media_url']) && !preg_match("/^https?:\/\//", $this->container['media_url'])) {
            $invalidProperties[] = "invalid value for 'media_url', must be conform to the pattern /^https?:\/\//.";
        }

        if (!is_null($this->container['media_base64']) && (mb_strlen($this->container['media_base64']) > 16000000)) {
            $invalidProperties[] = "invalid value for 'media_base64', the character length must be smaller than or equal to 16000000.";
        }

        $allowedValues = $this->getMediaMimeTypeAllowableValues();
        if (!is_null($this->container['media_mime_type']) && !in_array($this->container['media_mime_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'media_mime_type', must be one of '%s'",
                $this->container['media_mime_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['media_filename']) && (mb_strlen($this->container['media_filename']) > 255)) {
            $invalidProperties[] = "invalid value for 'media_filename', the character length must be smaller than or equal to 255.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets whatsapp_account_id
     *
     * @return string
     */
    public function getWhatsappAccountId()
    {
        return $this->container['whatsapp_account_id'];
    }

    /**
     * Sets whatsapp_account_id
     *
     * @param string $whatsapp_account_id whatsapp_account_id
     *
     * @return self
     */
    public function setWhatsappAccountId($whatsapp_account_id)
    {
        if (is_null($whatsapp_account_id)) {
            throw new \InvalidArgumentException('non-nullable whatsapp_account_id cannot be null');
        }
        $this->container['whatsapp_account_id'] = $whatsapp_account_id;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|null $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        if ((mb_strlen($country_code) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling BulkMessageRequest., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country_code) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling BulkMessageRequest., must be bigger than or equal to 2.');
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return string[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param string[] $recipients recipients
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }

        if ((count($recipients) < 1)) {
            throw new \InvalidArgumentException('invalid length for $recipients when calling BulkMessageRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        if ((mb_strlen($message) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $message when calling BulkMessageRequest., must be smaller than or equal to 4096.');
        }

        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        if ((mb_strlen($content) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $content when calling BulkMessageRequest., must be smaller than or equal to 4096.');
        }

        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets media_url
     *
     * @return string|null
     */
    public function getMediaUrl()
    {
        return $this->container['media_url'];
    }

    /**
     * Sets media_url
     *
     * @param string|null $media_url media_url
     *
     * @return self
     */
    public function setMediaUrl($media_url)
    {
        if (is_null($media_url)) {
            throw new \InvalidArgumentException('non-nullable media_url cannot be null');
        }

        if ((!preg_match("/^https?:\/\//", ObjectSerializer::toString($media_url)))) {
            throw new \InvalidArgumentException("invalid value for \$media_url when calling BulkMessageRequest., must conform to the pattern /^https?:\/\//.");
        }

        $this->container['media_url'] = $media_url;

        return $this;
    }

    /**
     * Gets media_base64
     *
     * @return string|null
     */
    public function getMediaBase64()
    {
        return $this->container['media_base64'];
    }

    /**
     * Sets media_base64
     *
     * @param string|null $media_base64 media_base64
     *
     * @return self
     */
    public function setMediaBase64($media_base64)
    {
        if (is_null($media_base64)) {
            throw new \InvalidArgumentException('non-nullable media_base64 cannot be null');
        }
        if ((mb_strlen($media_base64) > 16000000)) {
            throw new \InvalidArgumentException('invalid length for $media_base64 when calling BulkMessageRequest., must be smaller than or equal to 16000000.');
        }

        $this->container['media_base64'] = $media_base64;

        return $this;
    }

    /**
     * Gets media_mime_type
     *
     * @return string|null
     */
    public function getMediaMimeType()
    {
        return $this->container['media_mime_type'];
    }

    /**
     * Sets media_mime_type
     *
     * @param string|null $media_mime_type media_mime_type
     *
     * @return self
     */
    public function setMediaMimeType($media_mime_type)
    {
        if (is_null($media_mime_type)) {
            throw new \InvalidArgumentException('non-nullable media_mime_type cannot be null');
        }
        $allowedValues = $this->getMediaMimeTypeAllowableValues();
        if (!in_array($media_mime_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'media_mime_type', must be one of '%s'",
                    $media_mime_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['media_mime_type'] = $media_mime_type;

        return $this;
    }

    /**
     * Gets media_filename
     *
     * @return string|null
     */
    public function getMediaFilename()
    {
        return $this->container['media_filename'];
    }

    /**
     * Sets media_filename
     *
     * @param string|null $media_filename media_filename
     *
     * @return self
     */
    public function setMediaFilename($media_filename)
    {
        if (is_null($media_filename)) {
            throw new \InvalidArgumentException('non-nullable media_filename cannot be null');
        }
        if ((mb_strlen($media_filename) > 255)) {
            throw new \InvalidArgumentException('invalid length for $media_filename when calling BulkMessageRequest., must be smaller than or equal to 255.');
        }

        $this->container['media_filename'] = $media_filename;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


