<?php
/**
 * MessagingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Paygham
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Paygham Messaging API
 *
 * Public server-side API for sending WhatsApp messages and monitoring delivery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Paygham\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Paygham\ApiException;
use Paygham\Configuration;
use Paygham\FormDataProcessor;
use Paygham\HeaderSelector;
use Paygham\ObjectSerializer;

/**
 * MessagingApi Class Doc Comment
 *
 * @category Class
 * @package  Paygham
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getConnectionStatus' => [
            'application/json',
        ],
        'getDeliveryStatus' => [
            'application/json',
        ],
        'resumeDelivery' => [
            'application/json',
        ],
        'sendBulkMessages' => [
            'application/json',
        ],
        'sendMessage' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getConnectionStatus
     *
     * Check live WhatsApp connection status
     *
     * @param  string $whatsapp_account_id whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectionStatus'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paygham\Model\ConnectionStatusResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError
     */
    public function getConnectionStatus($whatsapp_account_id, string $contentType = self::contentTypes['getConnectionStatus'][0])
    {
        list($response) = $this->getConnectionStatusWithHttpInfo($whatsapp_account_id, $contentType);
        return $response;
    }

    /**
     * Operation getConnectionStatusWithHttpInfo
     *
     * Check live WhatsApp connection status
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectionStatus'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paygham\Model\ConnectionStatusResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConnectionStatusWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['getConnectionStatus'][0])
    {
        $request = $this->getConnectionStatusRequest($whatsapp_account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ConnectionStatusResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paygham\Model\ConnectionStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ConnectionStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConnectionStatusAsync
     *
     * Check live WhatsApp connection status
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectionStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectionStatusAsync($whatsapp_account_id, string $contentType = self::contentTypes['getConnectionStatus'][0])
    {
        return $this->getConnectionStatusAsyncWithHttpInfo($whatsapp_account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConnectionStatusAsyncWithHttpInfo
     *
     * Check live WhatsApp connection status
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectionStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConnectionStatusAsyncWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['getConnectionStatus'][0])
    {
        $returnType = '\Paygham\Model\ConnectionStatusResponse';
        $request = $this->getConnectionStatusRequest($whatsapp_account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConnectionStatus'
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConnectionStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConnectionStatusRequest($whatsapp_account_id, string $contentType = self::contentTypes['getConnectionStatus'][0])
    {

        // verify the required parameter 'whatsapp_account_id' is set
        if ($whatsapp_account_id === null || (is_array($whatsapp_account_id) && count($whatsapp_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $whatsapp_account_id when calling getConnectionStatus'
            );
        }


        $resourcePath = '/api/v1/messages/accounts/{whatsappAccountId}/connection-status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($whatsapp_account_id !== null) {
            $resourcePath = str_replace(
                '{whatsappAccountId}',
                ObjectSerializer::toPathValue($whatsapp_account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDeliveryStatus
     *
     * Get outbound delivery counts for an account
     *
     * @param  string $whatsapp_account_id whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDeliveryStatus'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paygham\Model\DeliveryStatusResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError
     */
    public function getDeliveryStatus($whatsapp_account_id, string $contentType = self::contentTypes['getDeliveryStatus'][0])
    {
        list($response) = $this->getDeliveryStatusWithHttpInfo($whatsapp_account_id, $contentType);
        return $response;
    }

    /**
     * Operation getDeliveryStatusWithHttpInfo
     *
     * Get outbound delivery counts for an account
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDeliveryStatus'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paygham\Model\DeliveryStatusResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDeliveryStatusWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['getDeliveryStatus'][0])
    {
        $request = $this->getDeliveryStatusRequest($whatsapp_account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\DeliveryStatusResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paygham\Model\DeliveryStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\DeliveryStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDeliveryStatusAsync
     *
     * Get outbound delivery counts for an account
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDeliveryStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDeliveryStatusAsync($whatsapp_account_id, string $contentType = self::contentTypes['getDeliveryStatus'][0])
    {
        return $this->getDeliveryStatusAsyncWithHttpInfo($whatsapp_account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDeliveryStatusAsyncWithHttpInfo
     *
     * Get outbound delivery counts for an account
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDeliveryStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDeliveryStatusAsyncWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['getDeliveryStatus'][0])
    {
        $returnType = '\Paygham\Model\DeliveryStatusResponse';
        $request = $this->getDeliveryStatusRequest($whatsapp_account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDeliveryStatus'
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDeliveryStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDeliveryStatusRequest($whatsapp_account_id, string $contentType = self::contentTypes['getDeliveryStatus'][0])
    {

        // verify the required parameter 'whatsapp_account_id' is set
        if ($whatsapp_account_id === null || (is_array($whatsapp_account_id) && count($whatsapp_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $whatsapp_account_id when calling getDeliveryStatus'
            );
        }


        $resourcePath = '/api/v1/messages/accounts/{whatsappAccountId}/delivery-status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($whatsapp_account_id !== null) {
            $resourcePath = str_replace(
                '{whatsappAccountId}',
                ObjectSerializer::toPathValue($whatsapp_account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resumeDelivery
     *
     * Requeue pending outbound messages after reconnect
     *
     * @param  string $whatsapp_account_id whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resumeDelivery'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paygham\Model\ResumeDeliveryResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError
     */
    public function resumeDelivery($whatsapp_account_id, string $contentType = self::contentTypes['resumeDelivery'][0])
    {
        list($response) = $this->resumeDeliveryWithHttpInfo($whatsapp_account_id, $contentType);
        return $response;
    }

    /**
     * Operation resumeDeliveryWithHttpInfo
     *
     * Requeue pending outbound messages after reconnect
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resumeDelivery'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paygham\Model\ResumeDeliveryResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function resumeDeliveryWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['resumeDelivery'][0])
    {
        $request = $this->resumeDeliveryRequest($whatsapp_account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ResumeDeliveryResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paygham\Model\ResumeDeliveryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ResumeDeliveryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resumeDeliveryAsync
     *
     * Requeue pending outbound messages after reconnect
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resumeDelivery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resumeDeliveryAsync($whatsapp_account_id, string $contentType = self::contentTypes['resumeDelivery'][0])
    {
        return $this->resumeDeliveryAsyncWithHttpInfo($whatsapp_account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resumeDeliveryAsyncWithHttpInfo
     *
     * Requeue pending outbound messages after reconnect
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resumeDelivery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resumeDeliveryAsyncWithHttpInfo($whatsapp_account_id, string $contentType = self::contentTypes['resumeDelivery'][0])
    {
        $returnType = '\Paygham\Model\ResumeDeliveryResponse';
        $request = $this->resumeDeliveryRequest($whatsapp_account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resumeDelivery'
     *
     * @param  string $whatsapp_account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resumeDelivery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resumeDeliveryRequest($whatsapp_account_id, string $contentType = self::contentTypes['resumeDelivery'][0])
    {

        // verify the required parameter 'whatsapp_account_id' is set
        if ($whatsapp_account_id === null || (is_array($whatsapp_account_id) && count($whatsapp_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $whatsapp_account_id when calling resumeDelivery'
            );
        }


        $resourcePath = '/api/v1/messages/accounts/{whatsappAccountId}/resume';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($whatsapp_account_id !== null) {
            $resourcePath = str_replace(
                '{whatsappAccountId}',
                ObjectSerializer::toPathValue($whatsapp_account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendBulkMessages
     *
     * Queue the same message for many recipients
     *
     * @param  string $idempotency_key Stable unique key for this batch. Each recipient is deduplicated independently. (required)
     * @param  \Paygham\Model\BulkMessageRequest $bulk_message_request bulk_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendBulkMessages'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paygham\Model\BulkMessageResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError
     */
    public function sendBulkMessages($idempotency_key, $bulk_message_request, string $contentType = self::contentTypes['sendBulkMessages'][0])
    {
        list($response) = $this->sendBulkMessagesWithHttpInfo($idempotency_key, $bulk_message_request, $contentType);
        return $response;
    }

    /**
     * Operation sendBulkMessagesWithHttpInfo
     *
     * Queue the same message for many recipients
     *
     * @param  string $idempotency_key Stable unique key for this batch. Each recipient is deduplicated independently. (required)
     * @param  \Paygham\Model\BulkMessageRequest $bulk_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendBulkMessages'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paygham\Model\BulkMessageResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendBulkMessagesWithHttpInfo($idempotency_key, $bulk_message_request, string $contentType = self::contentTypes['sendBulkMessages'][0])
    {
        $request = $this->sendBulkMessagesRequest($idempotency_key, $bulk_message_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\BulkMessageResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 413:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paygham\Model\BulkMessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\BulkMessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendBulkMessagesAsync
     *
     * Queue the same message for many recipients
     *
     * @param  string $idempotency_key Stable unique key for this batch. Each recipient is deduplicated independently. (required)
     * @param  \Paygham\Model\BulkMessageRequest $bulk_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendBulkMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendBulkMessagesAsync($idempotency_key, $bulk_message_request, string $contentType = self::contentTypes['sendBulkMessages'][0])
    {
        return $this->sendBulkMessagesAsyncWithHttpInfo($idempotency_key, $bulk_message_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendBulkMessagesAsyncWithHttpInfo
     *
     * Queue the same message for many recipients
     *
     * @param  string $idempotency_key Stable unique key for this batch. Each recipient is deduplicated independently. (required)
     * @param  \Paygham\Model\BulkMessageRequest $bulk_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendBulkMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendBulkMessagesAsyncWithHttpInfo($idempotency_key, $bulk_message_request, string $contentType = self::contentTypes['sendBulkMessages'][0])
    {
        $returnType = '\Paygham\Model\BulkMessageResponse';
        $request = $this->sendBulkMessagesRequest($idempotency_key, $bulk_message_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendBulkMessages'
     *
     * @param  string $idempotency_key Stable unique key for this batch. Each recipient is deduplicated independently. (required)
     * @param  \Paygham\Model\BulkMessageRequest $bulk_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendBulkMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendBulkMessagesRequest($idempotency_key, $bulk_message_request, string $contentType = self::contentTypes['sendBulkMessages'][0])
    {

        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling sendBulkMessages'
            );
        }
        if (strlen($idempotency_key) > 255) {
            throw new \InvalidArgumentException('invalid length for "$idempotency_key" when calling MessagingApi.sendBulkMessages, must be smaller than or equal to 255.');
        }
        if (strlen($idempotency_key) < 1) {
            throw new \InvalidArgumentException('invalid length for "$idempotency_key" when calling MessagingApi.sendBulkMessages, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'bulk_message_request' is set
        if ($bulk_message_request === null || (is_array($bulk_message_request) && count($bulk_message_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bulk_message_request when calling sendBulkMessages'
            );
        }


        $resourcePath = '/api/v1/messages/bulk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($bulk_message_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($bulk_message_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $bulk_message_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendMessage
     *
     * Send a WhatsApp message using an API key
     *
     * @param  string $idempotency_key Stable unique key for this business message. Reuse it when retrying the same request. (required)
     * @param  \Paygham\Model\SendMessageRequest $send_message_request send_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendMessage'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Paygham\Model\SendMessageResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError
     */
    public function sendMessage($idempotency_key, $send_message_request, string $contentType = self::contentTypes['sendMessage'][0])
    {
        list($response) = $this->sendMessageWithHttpInfo($idempotency_key, $send_message_request, $contentType);
        return $response;
    }

    /**
     * Operation sendMessageWithHttpInfo
     *
     * Send a WhatsApp message using an API key
     *
     * @param  string $idempotency_key Stable unique key for this business message. Reuse it when retrying the same request. (required)
     * @param  \Paygham\Model\SendMessageRequest $send_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendMessage'] to see the possible values for this operation
     *
     * @throws \Paygham\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Paygham\Model\SendMessageResponse|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError|\Paygham\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendMessageWithHttpInfo($idempotency_key, $send_message_request, string $contentType = self::contentTypes['sendMessage'][0])
    {
        $request = $this->sendMessageRequest($idempotency_key, $send_message_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\SendMessageResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 413:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
                case 502:
                    return $this->handleResponseWithDataType(
                        '\Paygham\Model\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Paygham\Model\SendMessageResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\SendMessageResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 502:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Paygham\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendMessageAsync
     *
     * Send a WhatsApp message using an API key
     *
     * @param  string $idempotency_key Stable unique key for this business message. Reuse it when retrying the same request. (required)
     * @param  \Paygham\Model\SendMessageRequest $send_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsync($idempotency_key, $send_message_request, string $contentType = self::contentTypes['sendMessage'][0])
    {
        return $this->sendMessageAsyncWithHttpInfo($idempotency_key, $send_message_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendMessageAsyncWithHttpInfo
     *
     * Send a WhatsApp message using an API key
     *
     * @param  string $idempotency_key Stable unique key for this business message. Reuse it when retrying the same request. (required)
     * @param  \Paygham\Model\SendMessageRequest $send_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsyncWithHttpInfo($idempotency_key, $send_message_request, string $contentType = self::contentTypes['sendMessage'][0])
    {
        $returnType = '\Paygham\Model\SendMessageResponse';
        $request = $this->sendMessageRequest($idempotency_key, $send_message_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendMessage'
     *
     * @param  string $idempotency_key Stable unique key for this business message. Reuse it when retrying the same request. (required)
     * @param  \Paygham\Model\SendMessageRequest $send_message_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendMessage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendMessageRequest($idempotency_key, $send_message_request, string $contentType = self::contentTypes['sendMessage'][0])
    {

        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling sendMessage'
            );
        }
        if (strlen($idempotency_key) > 255) {
            throw new \InvalidArgumentException('invalid length for "$idempotency_key" when calling MessagingApi.sendMessage, must be smaller than or equal to 255.');
        }
        if (strlen($idempotency_key) < 1) {
            throw new \InvalidArgumentException('invalid length for "$idempotency_key" when calling MessagingApi.sendMessage, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'send_message_request' is set
        if ($send_message_request === null || (is_array($send_message_request) && count($send_message_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $send_message_request when calling sendMessage'
            );
        }


        $resourcePath = '/api/v1/messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($send_message_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($send_message_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $send_message_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
