=begin
#Paygham Messaging API

#Public server-side API for sending WhatsApp messages and monitoring delivery.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

module Paygham
  VERSION = '0.1.0'
end
