/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectionStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionStatusResponse{}

// ConnectionStatusResponse struct for ConnectionStatusResponse
type ConnectionStatusResponse struct {
	Data ConnectionStatus `json:"data"`
}

type _ConnectionStatusResponse ConnectionStatusResponse

// NewConnectionStatusResponse instantiates a new ConnectionStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionStatusResponse(data ConnectionStatus) *ConnectionStatusResponse {
	this := ConnectionStatusResponse{}
	this.Data = data
	return &this
}

// NewConnectionStatusResponseWithDefaults instantiates a new ConnectionStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionStatusResponseWithDefaults() *ConnectionStatusResponse {
	this := ConnectionStatusResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ConnectionStatusResponse) GetData() ConnectionStatus {
	if o == nil {
		var ret ConnectionStatus
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatusResponse) GetDataOk() (*ConnectionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConnectionStatusResponse) SetData(v ConnectionStatus) {
	o.Data = v
}

func (o ConnectionStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ConnectionStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionStatusResponse := _ConnectionStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectionStatusResponse)

	if err != nil {
		return err
	}

	*o = ConnectionStatusResponse(varConnectionStatusResponse)

	return err
}

type NullableConnectionStatusResponse struct {
	value *ConnectionStatusResponse
	isSet bool
}

func (v NullableConnectionStatusResponse) Get() *ConnectionStatusResponse {
	return v.value
}

func (v *NullableConnectionStatusResponse) Set(val *ConnectionStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionStatusResponse(val *ConnectionStatusResponse) *NullableConnectionStatusResponse {
	return &NullableConnectionStatusResponse{value: val, isSet: true}
}

func (v NullableConnectionStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


