/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ConnectionStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionStatus{}

// ConnectionStatus struct for ConnectionStatus
type ConnectionStatus struct {
	AccountId string `json:"accountId"`
	Connected bool `json:"connected"`
	Stable bool `json:"stable"`
	AccountStatus string `json:"accountStatus"`
	EngineStatus string `json:"engineStatus"`
	SessionStatus string `json:"sessionStatus"`
	CheckedAt time.Time `json:"checkedAt"`
}

type _ConnectionStatus ConnectionStatus

// NewConnectionStatus instantiates a new ConnectionStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionStatus(accountId string, connected bool, stable bool, accountStatus string, engineStatus string, sessionStatus string, checkedAt time.Time) *ConnectionStatus {
	this := ConnectionStatus{}
	this.AccountId = accountId
	this.Connected = connected
	this.Stable = stable
	this.AccountStatus = accountStatus
	this.EngineStatus = engineStatus
	this.SessionStatus = sessionStatus
	this.CheckedAt = checkedAt
	return &this
}

// NewConnectionStatusWithDefaults instantiates a new ConnectionStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionStatusWithDefaults() *ConnectionStatus {
	this := ConnectionStatus{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *ConnectionStatus) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *ConnectionStatus) SetAccountId(v string) {
	o.AccountId = v
}

// GetConnected returns the Connected field value
func (o *ConnectionStatus) GetConnected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Connected
}

// GetConnectedOk returns a tuple with the Connected field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connected, true
}

// SetConnected sets field value
func (o *ConnectionStatus) SetConnected(v bool) {
	o.Connected = v
}

// GetStable returns the Stable field value
func (o *ConnectionStatus) GetStable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Stable
}

// GetStableOk returns a tuple with the Stable field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetStableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stable, true
}

// SetStable sets field value
func (o *ConnectionStatus) SetStable(v bool) {
	o.Stable = v
}

// GetAccountStatus returns the AccountStatus field value
func (o *ConnectionStatus) GetAccountStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetAccountStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountStatus, true
}

// SetAccountStatus sets field value
func (o *ConnectionStatus) SetAccountStatus(v string) {
	o.AccountStatus = v
}

// GetEngineStatus returns the EngineStatus field value
func (o *ConnectionStatus) GetEngineStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EngineStatus
}

// GetEngineStatusOk returns a tuple with the EngineStatus field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetEngineStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EngineStatus, true
}

// SetEngineStatus sets field value
func (o *ConnectionStatus) SetEngineStatus(v string) {
	o.EngineStatus = v
}

// GetSessionStatus returns the SessionStatus field value
func (o *ConnectionStatus) GetSessionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionStatus
}

// GetSessionStatusOk returns a tuple with the SessionStatus field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetSessionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionStatus, true
}

// SetSessionStatus sets field value
func (o *ConnectionStatus) SetSessionStatus(v string) {
	o.SessionStatus = v
}

// GetCheckedAt returns the CheckedAt field value
func (o *ConnectionStatus) GetCheckedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CheckedAt
}

// GetCheckedAtOk returns a tuple with the CheckedAt field value
// and a boolean to check if the value has been set.
func (o *ConnectionStatus) GetCheckedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckedAt, true
}

// SetCheckedAt sets field value
func (o *ConnectionStatus) SetCheckedAt(v time.Time) {
	o.CheckedAt = v
}

func (o ConnectionStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["connected"] = o.Connected
	toSerialize["stable"] = o.Stable
	toSerialize["accountStatus"] = o.AccountStatus
	toSerialize["engineStatus"] = o.EngineStatus
	toSerialize["sessionStatus"] = o.SessionStatus
	toSerialize["checkedAt"] = o.CheckedAt
	return toSerialize, nil
}

func (o *ConnectionStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"connected",
		"stable",
		"accountStatus",
		"engineStatus",
		"sessionStatus",
		"checkedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectionStatus := _ConnectionStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectionStatus)

	if err != nil {
		return err
	}

	*o = ConnectionStatus(varConnectionStatus)

	return err
}

type NullableConnectionStatus struct {
	value *ConnectionStatus
	isSet bool
}

func (v NullableConnectionStatus) Get() *ConnectionStatus {
	return v.value
}

func (v *NullableConnectionStatus) Set(val *ConnectionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionStatus(val *ConnectionStatus) *NullableConnectionStatus {
	return &NullableConnectionStatus{value: val, isSet: true}
}

func (v NullableConnectionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


