/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendMessageRequest{}

// SendMessageRequest struct for SendMessageRequest
type SendMessageRequest struct {
	WhatsappAccountId string `json:"whatsappAccountId"`
	// ISO country code; required for local numbers starting with 0
	CountryCode *string `json:"countryCode,omitempty"`
	// Destination phone (alias: recipient)
	To string `json:"to"`
	// Deprecated alias for to.
	// Deprecated
	Recipient *string `json:"recipient,omitempty"`
	// Text body (alias: content). Optional when media is provided.
	Message *string `json:"message,omitempty"`
	// Deprecated alias for message.
	// Deprecated
	Content *string `json:"content,omitempty"`
	// Public http(s) URL for an image or PDF. Mutually exclusive with mediaBase64.
	MediaUrl *string `json:"mediaUrl,omitempty" validate:"regexp=^https?://"`
	// Base64-encoded media. Mutually exclusive with mediaUrl.
	MediaBase64 *string `json:"mediaBase64,omitempty"`
	// Required when mediaUrl or mediaBase64 is set.
	MediaMimeType *string `json:"mediaMimeType,omitempty"`
	MediaFilename *string `json:"mediaFilename,omitempty"`
}

type _SendMessageRequest SendMessageRequest

// NewSendMessageRequest instantiates a new SendMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMessageRequest(whatsappAccountId string, to string) *SendMessageRequest {
	this := SendMessageRequest{}
	this.WhatsappAccountId = whatsappAccountId
	this.To = to
	return &this
}

// NewSendMessageRequestWithDefaults instantiates a new SendMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMessageRequestWithDefaults() *SendMessageRequest {
	this := SendMessageRequest{}
	return &this
}

// GetWhatsappAccountId returns the WhatsappAccountId field value
func (o *SendMessageRequest) GetWhatsappAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WhatsappAccountId
}

// GetWhatsappAccountIdOk returns a tuple with the WhatsappAccountId field value
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetWhatsappAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WhatsappAccountId, true
}

// SetWhatsappAccountId sets field value
func (o *SendMessageRequest) SetWhatsappAccountId(v string) {
	o.WhatsappAccountId = v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *SendMessageRequest) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *SendMessageRequest) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *SendMessageRequest) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetTo returns the To field value
func (o *SendMessageRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SendMessageRequest) SetTo(v string) {
	o.To = v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
// Deprecated
func (o *SendMessageRequest) GetRecipient() string {
	if o == nil || IsNil(o.Recipient) {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *SendMessageRequest) GetRecipientOk() (*string, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *SendMessageRequest) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
// Deprecated
func (o *SendMessageRequest) SetRecipient(v string) {
	o.Recipient = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SendMessageRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SendMessageRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SendMessageRequest) SetMessage(v string) {
	o.Message = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
// Deprecated
func (o *SendMessageRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *SendMessageRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SendMessageRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
// Deprecated
func (o *SendMessageRequest) SetContent(v string) {
	o.Content = &v
}

// GetMediaUrl returns the MediaUrl field value if set, zero value otherwise.
func (o *SendMessageRequest) GetMediaUrl() string {
	if o == nil || IsNil(o.MediaUrl) {
		var ret string
		return ret
	}
	return *o.MediaUrl
}

// GetMediaUrlOk returns a tuple with the MediaUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetMediaUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MediaUrl) {
		return nil, false
	}
	return o.MediaUrl, true
}

// HasMediaUrl returns a boolean if a field has been set.
func (o *SendMessageRequest) HasMediaUrl() bool {
	if o != nil && !IsNil(o.MediaUrl) {
		return true
	}

	return false
}

// SetMediaUrl gets a reference to the given string and assigns it to the MediaUrl field.
func (o *SendMessageRequest) SetMediaUrl(v string) {
	o.MediaUrl = &v
}

// GetMediaBase64 returns the MediaBase64 field value if set, zero value otherwise.
func (o *SendMessageRequest) GetMediaBase64() string {
	if o == nil || IsNil(o.MediaBase64) {
		var ret string
		return ret
	}
	return *o.MediaBase64
}

// GetMediaBase64Ok returns a tuple with the MediaBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetMediaBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.MediaBase64) {
		return nil, false
	}
	return o.MediaBase64, true
}

// HasMediaBase64 returns a boolean if a field has been set.
func (o *SendMessageRequest) HasMediaBase64() bool {
	if o != nil && !IsNil(o.MediaBase64) {
		return true
	}

	return false
}

// SetMediaBase64 gets a reference to the given string and assigns it to the MediaBase64 field.
func (o *SendMessageRequest) SetMediaBase64(v string) {
	o.MediaBase64 = &v
}

// GetMediaMimeType returns the MediaMimeType field value if set, zero value otherwise.
func (o *SendMessageRequest) GetMediaMimeType() string {
	if o == nil || IsNil(o.MediaMimeType) {
		var ret string
		return ret
	}
	return *o.MediaMimeType
}

// GetMediaMimeTypeOk returns a tuple with the MediaMimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetMediaMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaMimeType) {
		return nil, false
	}
	return o.MediaMimeType, true
}

// HasMediaMimeType returns a boolean if a field has been set.
func (o *SendMessageRequest) HasMediaMimeType() bool {
	if o != nil && !IsNil(o.MediaMimeType) {
		return true
	}

	return false
}

// SetMediaMimeType gets a reference to the given string and assigns it to the MediaMimeType field.
func (o *SendMessageRequest) SetMediaMimeType(v string) {
	o.MediaMimeType = &v
}

// GetMediaFilename returns the MediaFilename field value if set, zero value otherwise.
func (o *SendMessageRequest) GetMediaFilename() string {
	if o == nil || IsNil(o.MediaFilename) {
		var ret string
		return ret
	}
	return *o.MediaFilename
}

// GetMediaFilenameOk returns a tuple with the MediaFilename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageRequest) GetMediaFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.MediaFilename) {
		return nil, false
	}
	return o.MediaFilename, true
}

// HasMediaFilename returns a boolean if a field has been set.
func (o *SendMessageRequest) HasMediaFilename() bool {
	if o != nil && !IsNil(o.MediaFilename) {
		return true
	}

	return false
}

// SetMediaFilename gets a reference to the given string and assigns it to the MediaFilename field.
func (o *SendMessageRequest) SetMediaFilename(v string) {
	o.MediaFilename = &v
}

func (o SendMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["whatsappAccountId"] = o.WhatsappAccountId
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	toSerialize["to"] = o.To
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.MediaUrl) {
		toSerialize["mediaUrl"] = o.MediaUrl
	}
	if !IsNil(o.MediaBase64) {
		toSerialize["mediaBase64"] = o.MediaBase64
	}
	if !IsNil(o.MediaMimeType) {
		toSerialize["mediaMimeType"] = o.MediaMimeType
	}
	if !IsNil(o.MediaFilename) {
		toSerialize["mediaFilename"] = o.MediaFilename
	}
	return toSerialize, nil
}

func (o *SendMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"whatsappAccountId",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendMessageRequest := _SendMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendMessageRequest)

	if err != nil {
		return err
	}

	*o = SendMessageRequest(varSendMessageRequest)

	return err
}

type NullableSendMessageRequest struct {
	value *SendMessageRequest
	isSet bool
}

func (v NullableSendMessageRequest) Get() *SendMessageRequest {
	return v.value
}

func (v *NullableSendMessageRequest) Set(val *SendMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMessageRequest(val *SendMessageRequest) *NullableSendMessageRequest {
	return &NullableSendMessageRequest{value: val, isSet: true}
}

func (v NullableSendMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


