/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkMessageResponse{}

// BulkMessageResponse struct for BulkMessageResponse
type BulkMessageResponse struct {
	Success bool `json:"success"`
	Total int32 `json:"total"`
	Queued int32 `json:"queued"`
	ConsentRequested int32 `json:"consentRequested"`
	Rejected int32 `json:"rejected"`
	Results []BulkMessageResult `json:"results"`
}

type _BulkMessageResponse BulkMessageResponse

// NewBulkMessageResponse instantiates a new BulkMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkMessageResponse(success bool, total int32, queued int32, consentRequested int32, rejected int32, results []BulkMessageResult) *BulkMessageResponse {
	this := BulkMessageResponse{}
	this.Success = success
	this.Total = total
	this.Queued = queued
	this.ConsentRequested = consentRequested
	this.Rejected = rejected
	this.Results = results
	return &this
}

// NewBulkMessageResponseWithDefaults instantiates a new BulkMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkMessageResponseWithDefaults() *BulkMessageResponse {
	this := BulkMessageResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *BulkMessageResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BulkMessageResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetTotal returns the Total field value
func (o *BulkMessageResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *BulkMessageResponse) SetTotal(v int32) {
	o.Total = v
}

// GetQueued returns the Queued field value
func (o *BulkMessageResponse) GetQueued() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Queued
}

// GetQueuedOk returns a tuple with the Queued field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetQueuedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Queued, true
}

// SetQueued sets field value
func (o *BulkMessageResponse) SetQueued(v int32) {
	o.Queued = v
}

// GetConsentRequested returns the ConsentRequested field value
func (o *BulkMessageResponse) GetConsentRequested() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConsentRequested
}

// GetConsentRequestedOk returns a tuple with the ConsentRequested field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetConsentRequestedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsentRequested, true
}

// SetConsentRequested sets field value
func (o *BulkMessageResponse) SetConsentRequested(v int32) {
	o.ConsentRequested = v
}

// GetRejected returns the Rejected field value
func (o *BulkMessageResponse) GetRejected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rejected
}

// GetRejectedOk returns a tuple with the Rejected field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetRejectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rejected, true
}

// SetRejected sets field value
func (o *BulkMessageResponse) SetRejected(v int32) {
	o.Rejected = v
}

// GetResults returns the Results field value
func (o *BulkMessageResponse) GetResults() []BulkMessageResult {
	if o == nil {
		var ret []BulkMessageResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *BulkMessageResponse) GetResultsOk() ([]BulkMessageResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *BulkMessageResponse) SetResults(v []BulkMessageResult) {
	o.Results = v
}

func (o BulkMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["total"] = o.Total
	toSerialize["queued"] = o.Queued
	toSerialize["consentRequested"] = o.ConsentRequested
	toSerialize["rejected"] = o.Rejected
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *BulkMessageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"total",
		"queued",
		"consentRequested",
		"rejected",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkMessageResponse := _BulkMessageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkMessageResponse)

	if err != nil {
		return err
	}

	*o = BulkMessageResponse(varBulkMessageResponse)

	return err
}

type NullableBulkMessageResponse struct {
	value *BulkMessageResponse
	isSet bool
}

func (v NullableBulkMessageResponse) Get() *BulkMessageResponse {
	return v.value
}

func (v *NullableBulkMessageResponse) Set(val *BulkMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkMessageResponse(val *BulkMessageResponse) *NullableBulkMessageResponse {
	return &NullableBulkMessageResponse{value: val, isSet: true}
}

func (v NullableBulkMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


