/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendMessageResponse{}

// SendMessageResponse struct for SendMessageResponse
type SendMessageResponse struct {
	Success bool `json:"success"`
	MessageId NullableString `json:"messageId"`
	Status string `json:"status"`
	ConsentRequired *bool `json:"consentRequired,omitempty"`
	ConsentUrl NullableString `json:"consentUrl,omitempty"`
	Message *string `json:"message,omitempty"`
}

type _SendMessageResponse SendMessageResponse

// NewSendMessageResponse instantiates a new SendMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMessageResponse(success bool, messageId NullableString, status string) *SendMessageResponse {
	this := SendMessageResponse{}
	this.Success = success
	this.MessageId = messageId
	this.Status = status
	return &this
}

// NewSendMessageResponseWithDefaults instantiates a new SendMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMessageResponseWithDefaults() *SendMessageResponse {
	this := SendMessageResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *SendMessageResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SendMessageResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessageId returns the MessageId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SendMessageResponse) GetMessageId() string {
	if o == nil || o.MessageId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MessageId.Get()
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendMessageResponse) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageId.Get(), o.MessageId.IsSet()
}

// SetMessageId sets field value
func (o *SendMessageResponse) SetMessageId(v string) {
	o.MessageId.Set(&v)
}

// GetStatus returns the Status field value
func (o *SendMessageResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SendMessageResponse) SetStatus(v string) {
	o.Status = v
}

// GetConsentRequired returns the ConsentRequired field value if set, zero value otherwise.
func (o *SendMessageResponse) GetConsentRequired() bool {
	if o == nil || IsNil(o.ConsentRequired) {
		var ret bool
		return ret
	}
	return *o.ConsentRequired
}

// GetConsentRequiredOk returns a tuple with the ConsentRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetConsentRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.ConsentRequired) {
		return nil, false
	}
	return o.ConsentRequired, true
}

// HasConsentRequired returns a boolean if a field has been set.
func (o *SendMessageResponse) HasConsentRequired() bool {
	if o != nil && !IsNil(o.ConsentRequired) {
		return true
	}

	return false
}

// SetConsentRequired gets a reference to the given bool and assigns it to the ConsentRequired field.
func (o *SendMessageResponse) SetConsentRequired(v bool) {
	o.ConsentRequired = &v
}

// GetConsentUrl returns the ConsentUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendMessageResponse) GetConsentUrl() string {
	if o == nil || IsNil(o.ConsentUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ConsentUrl.Get()
}

// GetConsentUrlOk returns a tuple with the ConsentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendMessageResponse) GetConsentUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsentUrl.Get(), o.ConsentUrl.IsSet()
}

// HasConsentUrl returns a boolean if a field has been set.
func (o *SendMessageResponse) HasConsentUrl() bool {
	if o != nil && o.ConsentUrl.IsSet() {
		return true
	}

	return false
}

// SetConsentUrl gets a reference to the given NullableString and assigns it to the ConsentUrl field.
func (o *SendMessageResponse) SetConsentUrl(v string) {
	o.ConsentUrl.Set(&v)
}
// SetConsentUrlNil sets the value for ConsentUrl to be an explicit nil
func (o *SendMessageResponse) SetConsentUrlNil() {
	o.ConsentUrl.Set(nil)
}

// UnsetConsentUrl ensures that no value is present for ConsentUrl, not even an explicit nil
func (o *SendMessageResponse) UnsetConsentUrl() {
	o.ConsentUrl.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SendMessageResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SendMessageResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SendMessageResponse) SetMessage(v string) {
	o.Message = &v
}

func (o SendMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["messageId"] = o.MessageId.Get()
	toSerialize["status"] = o.Status
	if !IsNil(o.ConsentRequired) {
		toSerialize["consentRequired"] = o.ConsentRequired
	}
	if o.ConsentUrl.IsSet() {
		toSerialize["consentUrl"] = o.ConsentUrl.Get()
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *SendMessageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"messageId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendMessageResponse := _SendMessageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendMessageResponse)

	if err != nil {
		return err
	}

	*o = SendMessageResponse(varSendMessageResponse)

	return err
}

type NullableSendMessageResponse struct {
	value *SendMessageResponse
	isSet bool
}

func (v NullableSendMessageResponse) Get() *SendMessageResponse {
	return v.value
}

func (v *NullableSendMessageResponse) Set(val *SendMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMessageResponse(val *SendMessageResponse) *NullableSendMessageResponse {
	return &NullableSendMessageResponse{value: val, isSet: true}
}

func (v NullableSendMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


