/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResumeDeliveryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResumeDeliveryResponse{}

// ResumeDeliveryResponse struct for ResumeDeliveryResponse
type ResumeDeliveryResponse struct {
	Data ResumeDelivery `json:"data"`
}

type _ResumeDeliveryResponse ResumeDeliveryResponse

// NewResumeDeliveryResponse instantiates a new ResumeDeliveryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResumeDeliveryResponse(data ResumeDelivery) *ResumeDeliveryResponse {
	this := ResumeDeliveryResponse{}
	this.Data = data
	return &this
}

// NewResumeDeliveryResponseWithDefaults instantiates a new ResumeDeliveryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResumeDeliveryResponseWithDefaults() *ResumeDeliveryResponse {
	this := ResumeDeliveryResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ResumeDeliveryResponse) GetData() ResumeDelivery {
	if o == nil {
		var ret ResumeDelivery
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResumeDeliveryResponse) GetDataOk() (*ResumeDelivery, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResumeDeliveryResponse) SetData(v ResumeDelivery) {
	o.Data = v
}

func (o ResumeDeliveryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResumeDeliveryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResumeDeliveryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResumeDeliveryResponse := _ResumeDeliveryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResumeDeliveryResponse)

	if err != nil {
		return err
	}

	*o = ResumeDeliveryResponse(varResumeDeliveryResponse)

	return err
}

type NullableResumeDeliveryResponse struct {
	value *ResumeDeliveryResponse
	isSet bool
}

func (v NullableResumeDeliveryResponse) Get() *ResumeDeliveryResponse {
	return v.value
}

func (v *NullableResumeDeliveryResponse) Set(val *ResumeDeliveryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResumeDeliveryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResumeDeliveryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResumeDeliveryResponse(val *ResumeDeliveryResponse) *NullableResumeDeliveryResponse {
	return &NullableResumeDeliveryResponse{value: val, isSet: true}
}

func (v NullableResumeDeliveryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResumeDeliveryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


