/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliveryStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryStatusResponse{}

// DeliveryStatusResponse struct for DeliveryStatusResponse
type DeliveryStatusResponse struct {
	Data DeliveryStatus `json:"data"`
}

type _DeliveryStatusResponse DeliveryStatusResponse

// NewDeliveryStatusResponse instantiates a new DeliveryStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryStatusResponse(data DeliveryStatus) *DeliveryStatusResponse {
	this := DeliveryStatusResponse{}
	this.Data = data
	return &this
}

// NewDeliveryStatusResponseWithDefaults instantiates a new DeliveryStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryStatusResponseWithDefaults() *DeliveryStatusResponse {
	this := DeliveryStatusResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DeliveryStatusResponse) GetData() DeliveryStatus {
	if o == nil {
		var ret DeliveryStatus
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeliveryStatusResponse) GetDataOk() (*DeliveryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeliveryStatusResponse) SetData(v DeliveryStatus) {
	o.Data = v
}

func (o DeliveryStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeliveryStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryStatusResponse := _DeliveryStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryStatusResponse)

	if err != nil {
		return err
	}

	*o = DeliveryStatusResponse(varDeliveryStatusResponse)

	return err
}

type NullableDeliveryStatusResponse struct {
	value *DeliveryStatusResponse
	isSet bool
}

func (v NullableDeliveryStatusResponse) Get() *DeliveryStatusResponse {
	return v.value
}

func (v *NullableDeliveryStatusResponse) Set(val *DeliveryStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryStatusResponse(val *DeliveryStatusResponse) *NullableDeliveryStatusResponse {
	return &NullableDeliveryStatusResponse{value: val, isSet: true}
}

func (v NullableDeliveryStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


