/*
Paygham Messaging API

Public server-side API for sending WhatsApp messages and monitoring delivery.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paygham

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkMessageRequest{}

// BulkMessageRequest struct for BulkMessageRequest
type BulkMessageRequest struct {
	WhatsappAccountId string `json:"whatsappAccountId"`
	CountryCode *string `json:"countryCode,omitempty"`
	Recipients []string `json:"recipients"`
	Message *string `json:"message,omitempty"`
	Content *string `json:"content,omitempty"`
	MediaUrl *string `json:"mediaUrl,omitempty" validate:"regexp=^https?://"`
	MediaBase64 *string `json:"mediaBase64,omitempty"`
	MediaMimeType *string `json:"mediaMimeType,omitempty"`
	MediaFilename *string `json:"mediaFilename,omitempty"`
}

type _BulkMessageRequest BulkMessageRequest

// NewBulkMessageRequest instantiates a new BulkMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkMessageRequest(whatsappAccountId string, recipients []string) *BulkMessageRequest {
	this := BulkMessageRequest{}
	this.WhatsappAccountId = whatsappAccountId
	this.Recipients = recipients
	return &this
}

// NewBulkMessageRequestWithDefaults instantiates a new BulkMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkMessageRequestWithDefaults() *BulkMessageRequest {
	this := BulkMessageRequest{}
	return &this
}

// GetWhatsappAccountId returns the WhatsappAccountId field value
func (o *BulkMessageRequest) GetWhatsappAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WhatsappAccountId
}

// GetWhatsappAccountIdOk returns a tuple with the WhatsappAccountId field value
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetWhatsappAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WhatsappAccountId, true
}

// SetWhatsappAccountId sets field value
func (o *BulkMessageRequest) SetWhatsappAccountId(v string) {
	o.WhatsappAccountId = v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *BulkMessageRequest) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetRecipients returns the Recipients field value
func (o *BulkMessageRequest) GetRecipients() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetRecipientsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipients, true
}

// SetRecipients sets field value
func (o *BulkMessageRequest) SetRecipients(v []string) {
	o.Recipients = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *BulkMessageRequest) SetMessage(v string) {
	o.Message = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *BulkMessageRequest) SetContent(v string) {
	o.Content = &v
}

// GetMediaUrl returns the MediaUrl field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetMediaUrl() string {
	if o == nil || IsNil(o.MediaUrl) {
		var ret string
		return ret
	}
	return *o.MediaUrl
}

// GetMediaUrlOk returns a tuple with the MediaUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetMediaUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MediaUrl) {
		return nil, false
	}
	return o.MediaUrl, true
}

// HasMediaUrl returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasMediaUrl() bool {
	if o != nil && !IsNil(o.MediaUrl) {
		return true
	}

	return false
}

// SetMediaUrl gets a reference to the given string and assigns it to the MediaUrl field.
func (o *BulkMessageRequest) SetMediaUrl(v string) {
	o.MediaUrl = &v
}

// GetMediaBase64 returns the MediaBase64 field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetMediaBase64() string {
	if o == nil || IsNil(o.MediaBase64) {
		var ret string
		return ret
	}
	return *o.MediaBase64
}

// GetMediaBase64Ok returns a tuple with the MediaBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetMediaBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.MediaBase64) {
		return nil, false
	}
	return o.MediaBase64, true
}

// HasMediaBase64 returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasMediaBase64() bool {
	if o != nil && !IsNil(o.MediaBase64) {
		return true
	}

	return false
}

// SetMediaBase64 gets a reference to the given string and assigns it to the MediaBase64 field.
func (o *BulkMessageRequest) SetMediaBase64(v string) {
	o.MediaBase64 = &v
}

// GetMediaMimeType returns the MediaMimeType field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetMediaMimeType() string {
	if o == nil || IsNil(o.MediaMimeType) {
		var ret string
		return ret
	}
	return *o.MediaMimeType
}

// GetMediaMimeTypeOk returns a tuple with the MediaMimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetMediaMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaMimeType) {
		return nil, false
	}
	return o.MediaMimeType, true
}

// HasMediaMimeType returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasMediaMimeType() bool {
	if o != nil && !IsNil(o.MediaMimeType) {
		return true
	}

	return false
}

// SetMediaMimeType gets a reference to the given string and assigns it to the MediaMimeType field.
func (o *BulkMessageRequest) SetMediaMimeType(v string) {
	o.MediaMimeType = &v
}

// GetMediaFilename returns the MediaFilename field value if set, zero value otherwise.
func (o *BulkMessageRequest) GetMediaFilename() string {
	if o == nil || IsNil(o.MediaFilename) {
		var ret string
		return ret
	}
	return *o.MediaFilename
}

// GetMediaFilenameOk returns a tuple with the MediaFilename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkMessageRequest) GetMediaFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.MediaFilename) {
		return nil, false
	}
	return o.MediaFilename, true
}

// HasMediaFilename returns a boolean if a field has been set.
func (o *BulkMessageRequest) HasMediaFilename() bool {
	if o != nil && !IsNil(o.MediaFilename) {
		return true
	}

	return false
}

// SetMediaFilename gets a reference to the given string and assigns it to the MediaFilename field.
func (o *BulkMessageRequest) SetMediaFilename(v string) {
	o.MediaFilename = &v
}

func (o BulkMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["whatsappAccountId"] = o.WhatsappAccountId
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	toSerialize["recipients"] = o.Recipients
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.MediaUrl) {
		toSerialize["mediaUrl"] = o.MediaUrl
	}
	if !IsNil(o.MediaBase64) {
		toSerialize["mediaBase64"] = o.MediaBase64
	}
	if !IsNil(o.MediaMimeType) {
		toSerialize["mediaMimeType"] = o.MediaMimeType
	}
	if !IsNil(o.MediaFilename) {
		toSerialize["mediaFilename"] = o.MediaFilename
	}
	return toSerialize, nil
}

func (o *BulkMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"whatsappAccountId",
		"recipients",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkMessageRequest := _BulkMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkMessageRequest)

	if err != nil {
		return err
	}

	*o = BulkMessageRequest(varBulkMessageRequest)

	return err
}

type NullableBulkMessageRequest struct {
	value *BulkMessageRequest
	isSet bool
}

func (v NullableBulkMessageRequest) Get() *BulkMessageRequest {
	return v.value
}

func (v *NullableBulkMessageRequest) Set(val *BulkMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkMessageRequest(val *BulkMessageRequest) *NullableBulkMessageRequest {
	return &NullableBulkMessageRequest{value: val, isSet: true}
}

func (v NullableBulkMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


